'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmBankOrder_EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmBankOrder-EN", GetType(frmBankOrder_EN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bus date.
        '''</summary>
        Friend Shared ReadOnly Property AFFECTDATE() As String
            Get
                Return ResourceManager.GetString("AFFECTDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total amt..
        '''</summary>
        Friend Shared ReadOnly Property AMT() As String
            Get
                Return ResourceManager.GetString("AMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã ngân hàng.
        '''</summary>
        Friend Shared ReadOnly Property BANKCODE() As String
            Get
                Return ResourceManager.GetString("BANKCODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancel() As String
            Get
                Return ResourceManager.GetString("btnCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kết xuất.
        '''</summary>
        Friend Shared ReadOnly Property btnExport() As String
            Get
                Return ResourceManager.GetString("btnExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit.
        '''</summary>
        Friend Shared ReadOnly Property btnSubmit() As String
            Get
                Return ResourceManager.GetString("btnSubmit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check status:.
        '''</summary>
        Friend Shared ReadOnly Property CHECKSTATUS() As String
            Get
                Return ResourceManager.GetString("CHECKSTATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create date.
        '''</summary>
        Friend Shared ReadOnly Property CRDATE() As String
            Get
                Return ResourceManager.GetString("CRDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create time.
        '''</summary>
        Friend Shared ReadOnly Property CREATETST() As String
            Get
                Return ResourceManager.GetString("CREATETST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property DESC_STATUS() As String
            Get
                Return ResourceManager.GetString("DESC_STATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error desc..
        '''</summary>
        Friend Shared ReadOnly Property ERRDESC() As String
            Get
                Return ResourceManager.GetString("ERRDESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Xem trạng thái Hold/Unhold bảng kê sang ngân hàng.
        '''</summary>
        Friend Shared ReadOnly Property frmBankOrder() As String
            Get
                Return ResourceManager.GetString("frmBankOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank.
        '''</summary>
        Friend Shared ReadOnly Property REFBANK() As String
            Get
                Return ResourceManager.GetString("REFBANK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receive time.
        '''</summary>
        Friend Shared ReadOnly Property SENDTST() As String
            Get
                Return ResourceManager.GetString("SENDTST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã bảng kê.
        '''</summary>
        Friend Shared ReadOnly Property TRFCODE() As String
            Get
                Return ResourceManager.GetString("TRFCODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trading date.
        '''</summary>
        Friend Shared ReadOnly Property TXDATE() As String
            Get
                Return ResourceManager.GetString("TXDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property VERSION() As String
            Get
                Return ResourceManager.GetString("VERSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mã giao dịch.
        '''</summary>
        Friend Shared ReadOnly Property VERSIONLOCAL() As String
            Get
                Return ResourceManager.GetString("VERSIONLOCAL", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
