'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmCFLNKAP_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmCFLNKAP-VN", GetType(frmCFLNKAP_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã loại hình.
    '''</summary>
    Friend Shared ReadOnly Property ACTYPE() As String
        Get
            Return ResourceManager.GetString("ACTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thêm mới dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property AddnewSuccessful() As String
        Get
            Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tiểu khoản:.
    '''</summary>
    Friend Shared ReadOnly Property AFACCTNO() As String
        Get
            Return ResourceManager.GetString("AFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Đồng ý.
    '''</summary>
    Friend Shared ReadOnly Property btnApply() As String
        Get
            Return ResourceManager.GetString("btnApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số lưu ký.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sửa dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property EditSuccessful() As String
        Get
            Return ResourceManager.GetString("EditSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày hiệu lực phải lớn hơn hay bằng ngày hiện tại!.
    '''</summary>
    Friend Shared ReadOnly Property EFFDATE_GREATER_BUSDATE() As String
        Get
            Return ResourceManager.GetString("EFFDATE_GREATER_BUSDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày hết hạn.
    '''</summary>
    Friend Shared ReadOnly Property EXPDATE() As String
        Get
            Return ResourceManager.GetString("EXPDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày hết hạn phải lớn hơn hay bằng ngày hiệu lực!.
    '''</summary>
    Friend Shared ReadOnly Property EXPDATE_GREATER_EFFDATE() As String
        Get
            Return ResourceManager.GetString("EXPDATE_GREATER_EFFDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quản lý giao dịch bị chặn.
    '''</summary>
    Friend Shared ReadOnly Property frmAFTXMAP() As String
        Get
            Return ResourceManager.GetString("frmAFTXMAP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin giao dịch bị chặn.
    '''</summary>
    Friend Shared ReadOnly Property grbTXMAP() As String
        Get
            Return ResourceManager.GetString("grbTXMAP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không khởi tạo được cửa sổ!.
    '''</summary>
    Friend Shared ReadOnly Property InitDialogFailed() As String
        Get
            Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin giao dịch bị chặn..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption0() As String
        Get
            Return ResourceManager.GetString("lblCaption0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thêm mới giao dịch bị chặn..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption1() As String
        Get
            Return ResourceManager.GetString("lblCaption1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sửa hợp đồng báo cáo..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption2() As String
        Get
            Return ResourceManager.GetString("lblCaption2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường [@] không được để trống!.
    '''</summary>
    Friend Shared ReadOnly Property Mandatory() As String
        Get
            Return ResourceManager.GetString("Mandatory", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã người được ủy quyền.
    '''</summary>
    Friend Shared ReadOnly Property REFID() As String
        Get
            Return ResourceManager.GetString("REFID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không thể thêm mới giao dịch bị chặn!.
    '''</summary>
    Friend Shared ReadOnly Property SavingFailed() As String
        Get
            Return ResourceManager.GetString("SavingFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã người làm.
    '''</summary>
    Friend Shared ReadOnly Property TLID() As String
        Get
            Return ResourceManager.GetString("TLID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property TLTXCD() As String
        Get
            Return ResourceManager.GetString("TLTXCD", resourceCulture)
        End Get
    End Property
End Class
