'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmCreateDFGRDeal_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmCreateDFGRDeal-VN", GetType(frmCreateDFGRDeal_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản giao dịch và số tiểu khoản HĐ vay thanh lý không giống nhau. Đề nghị nhập lại!.
    '''</summary>
    Friend Shared ReadOnly Property AFACCTNO_IS_NOT_MATCHING() As String
        Get
            Return ResourceManager.GetString("AFACCTNO_IS_NOT_MATCHING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản giao dịch và số tiểu khoản trên chứng khoán tạo HĐ vay không giống nhau. Đề nghị nhập lại!.
    '''</summary>
    Friend Shared ReadOnly Property AFACCTNO_IS_NOT_MATCHING2() As String
        Get
            Return ResourceManager.GetString("AFACCTNO_IS_NOT_MATCHING2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có duyệt giao dịch không?.
    '''</summary>
    Friend Shared ReadOnly Property ApproveConfirm() As String
        Get
            Return ResourceManager.GetString("ApproveConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tự tăng.
    '''</summary>
    Friend Shared ReadOnly Property AUTOID() As String
        Get
            Return ResourceManager.GetString("AUTOID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CK được rút.
    '''</summary>
    Friend Shared ReadOnly Property AVLWITHDRAW() As String
        Get
            Return ResourceManager.GetString("AVLWITHDRAW", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư không đủ để đăng ký mua quyền !.
    '''</summary>
    Friend Shared ReadOnly Property BALNOTENOUGH() As String
        Get
            Return ResourceManager.GetString("BALNOTENOUGH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng nhập vào lớn hơn khối lượng có thể thực hiện block forward !.
    '''</summary>
    Friend Shared ReadOnly Property BFWQTTYLESSQTTY() As String
        Get
            Return ResourceManager.GetString("BFWQTTYLESSQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thêm.
    '''</summary>
    Friend Shared ReadOnly Property btnAdd() As String
        Get
            Return ResourceManager.GetString("btnAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Hiệu chỉnh.
    '''</summary>
    Friend Shared ReadOnly Property btnAdjust() As String
        Get
            Return ResourceManager.GetString("btnAdjust", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Duyệt.
    '''</summary>
    Friend Shared ReadOnly Property btnApprove() As String
        Get
            Return ResourceManager.GetString("btnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Thoát.
    '''</summary>
    Friend Shared ReadOnly Property btnCANCEL() As String
        Get
            Return ResourceManager.GetString("btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Xóa.
    '''</summary>
    Friend Shared ReadOnly Property btnDEL() As String
        Get
            Return ResourceManager.GetString("btnDEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ?.
    '''</summary>
    Friend Shared ReadOnly Property btnGetDeal() As String
        Get
            Return ResourceManager.GetString("btnGetDeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chấp nhận.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Hủy.
    '''</summary>
    Friend Shared ReadOnly Property btnReject() As String
        Get
            Return ResourceManager.GetString("btnReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tự động giải ngân.
    '''</summary>
    Friend Shared ReadOnly Property chkAUTODRAWNDOWN() As String
        Get
            Return ResourceManager.GetString("chkAUTODRAWNDOWN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thanh lý tái ký.
    '''</summary>
    Friend Shared ReadOnly Property chkENDNEWDEAL() As String
        Get
            Return ResourceManager.GetString("chkENDNEWDEAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Có cần duyệt không?.
    '''</summary>
    Friend Shared ReadOnly Property chkisapprove() As String
        Get
            Return ResourceManager.GetString("chkisapprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vay dựa trên chứng khoán chờ về theo sự kiện quyền mua chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property chkOPTIONSTOCK() As String
        Get
            Return ResourceManager.GetString("chkOPTIONSTOCK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày TT.
    '''</summary>
    Friend Shared ReadOnly Property CLEARDATE() As String
        Get
            Return ResourceManager.GetString("CLEARDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tham chiếu không hợp lệ.
    '''</summary>
    Friend Shared ReadOnly Property DEALINVALID() As String
        Get
            Return ResourceManager.GetString("DEALINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tạo hợp đồng DF.
    '''</summary>
    Friend Shared ReadOnly Property DESC2670() As String
        Get
            Return ResourceManager.GetString("DESC2670", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ứng trước tiền cổ tức {0}, ngày {1}.
    '''</summary>
    Friend Shared ReadOnly Property DescCACash() As String
        Get
            Return ResourceManager.GetString("DescCACash", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_AFACCTNO() As String
        Get
            Return ResourceManager.GetString("DFGR_AFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền giải ngân.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_AMT() As String
        Get
            Return ResourceManager.GetString("DFGR_AMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá cho vay.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_DFPRICE() As String
        Get
            Return ResourceManager.GetString("DFGR_DFPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tỷ lệ cho vay.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_DFRATE() As String
        Get
            Return ResourceManager.GetString("DFGR_DFRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_DTYPE() As String
        Get
            Return ResourceManager.GetString("DFGR_DTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sl ck.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_QTTY() As String
        Get
            Return ResourceManager.GetString("DFGR_QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã liên quan.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_REF() As String
        Get
            Return ResourceManager.GetString("DFGR_REF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property DFGR_SYMBOL() As String
        Get
            Return ResourceManager.GetString("DFGR_SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá cho vay không được lớn hơn giá tham chiếu!.
    '''</summary>
    Friend Shared ReadOnly Property DFPRICE_OVER_REFPRICE() As String
        Get
            Return ResourceManager.GetString("DFPRICE_OVER_REFPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại hình DF không hợp lệ hoặc chưa gán rổ chứng khoán cho loại hình!.
    '''</summary>
    Friend Shared ReadOnly Property DFTYPEINVALID() As String
        Get
            Return ResourceManager.GetString("DFTYPEINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chỉ được phép tạo 1 deal với tiền CA chờ về!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_BLOCK_CA_ONLYONE() As String
        Get
            Return ResourceManager.GetString("ERR_BLOCK_CA_ONLYONE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy thông tin tiểu khoản!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CF_CONTRACT_NOT_FOUND() As String
        Get
            Return ResourceManager.GetString("ERR_CF_CONTRACT_NOT_FOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không thuộc nhóm quản lý khách hàng.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CF_NOT_CAREBY() As String
        Get
            Return ResourceManager.GetString("ERR_CF_NOT_CAREBY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường không thể trống !.
    '''</summary>
    Friend Shared ReadOnly Property ERR_FIELD_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_FIELD_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền giải ngân không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INV_AMOUNT() As String
        Get
            Return ResourceManager.GetString("ERR_INV_AMOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tỉ lệ vay không được = 0.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INV_RATE() As String
        Get
            Return ResourceManager.GetString("ERR_INV_RATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản giải ngân không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_DIS_ACCOUNT() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_DIS_ACCOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản chứng khoán cầm cố không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_STK_ACCOUNT() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_STK_ACCOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không có mã chứng khoán nào được cầm cố!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NULL_STOCK() As String
        Get
            Return ResourceManager.GetString("ERR_NULL_STOCK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng chứng khoán tạo Deal phải tròn lô giao dịch !.
    '''</summary>
    Friend Shared ReadOnly Property ERR_QTTY_NOT_TRADELOT() As String
        Get
            Return ResourceManager.GetString("ERR_QTTY_NOT_TRADELOT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thông tin chứng khoán không đúng !.
    '''</summary>
    Friend Shared ReadOnly Property ERR_SEC_INFO() As String
        Get
            Return ResourceManager.GetString("ERR_SEC_INFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tạo deal .
    '''</summary>
    Friend Shared ReadOnly Property frmCreateDFDeal() As String
        Get
            Return ResourceManager.GetString("frmCreateDFDeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tạo deal tổng DF.
    '''</summary>
    Friend Shared ReadOnly Property frmCreateDFGRDeal() As String
        Get
            Return ResourceManager.GetString("frmCreateDFGRDeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng nhập vào lớn hơn khối lượng có thể forward !.
    '''</summary>
    Friend Shared ReadOnly Property FWQTTYLESSQTTY() As String
        Get
            Return ResourceManager.GetString("FWQTTYLESSQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong trường hợp thanh lý tái ký thì Tự động giải ngân phải là bắt buộc !.
    '''</summary>
    Friend Shared ReadOnly Property HASTOAUTODRAWNDOWN() As String
        Get
            Return ResourceManager.GetString("HASTOAUTODRAWNDOWN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản không có loại chứng khoán này..
    '''</summary>
    Friend Shared ReadOnly Property INVALID_SYMBOL() As String
        Get
            Return ResourceManager.GetString("INVALID_SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã sản phẩm.
    '''</summary>
    Friend Shared ReadOnly Property lblAcType() As String
        Get
            Return ResourceManager.GetString("lblAcType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property lblAFACCCBO() As String
        Get
            Return ResourceManager.GetString("lblAFACCCBO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property lblAFACCTNO() As String
        Get
            Return ResourceManager.GetString("lblAFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiểu khoản giải ngân.
    '''</summary>
    Friend Shared ReadOnly Property LBLAFACCTNODRD() As String
        Get
            Return ResourceManager.GetString("LBLAFACCTNODRD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền nộp thêm.
    '''</summary>
    Friend Shared ReadOnly Property lblBALADDOPT() As String
        Get
            Return ResourceManager.GetString("lblBALADDOPT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư khả dụng.
    '''</summary>
    Friend Shared ReadOnly Property lblBALDEFOVD() As String
        Get
            Return ResourceManager.GetString("lblBALDEFOVD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền ứng trước.
    '''</summary>
    Friend Shared ReadOnly Property lblCIAdvance() As String
        Get
            Return ResourceManager.GetString("lblCIAdvance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư.
    '''</summary>
    Friend Shared ReadOnly Property lblCIBalance() As String
        Get
            Return ResourceManager.GetString("lblCIBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số lưu ký.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("lblCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nội dung.
    '''</summary>
    Friend Shared ReadOnly Property lblDescription() As String
        Get
            Return ResourceManager.GetString("lblDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị vay.
    '''</summary>
    Friend Shared ReadOnly Property lblDFAMT() As String
        Get
            Return ResourceManager.GetString("lblDFAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Biểu phí.
    '''</summary>
    Friend Shared ReadOnly Property lblDFFeemap() As String
        Get
            Return ResourceManager.GetString("lblDFFeemap", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá cho vay.
    '''</summary>
    Friend Shared ReadOnly Property lblDFPrice() As String
        Get
            Return ResourceManager.GetString("lblDFPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TL vay(%).
    '''</summary>
    Friend Shared ReadOnly Property lblDFRATE() As String
        Get
            Return ResourceManager.GetString("lblDFRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị phí.
    '''</summary>
    Friend Shared ReadOnly Property lblFeeAmt() As String
        Get
            Return ResourceManager.GetString("lblFeeAmt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tỷ lệ phí.
    '''</summary>
    Friend Shared ReadOnly Property lblFeeRate() As String
        Get
            Return ResourceManager.GetString("lblFeeRate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TL an toàn(%).
    '''</summary>
    Friend Shared ReadOnly Property lblIRATE() As String
        Get
            Return ResourceManager.GetString("lblIRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TL xử lý(%).
    '''</summary>
    Friend Shared ReadOnly Property lblLRATE() As String
        Get
            Return ResourceManager.GetString("lblLRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị khớp [chưa bao gồm phí và VAT].
    '''</summary>
    Friend Shared ReadOnly Property lblMATVAL() As String
        Get
            Return ResourceManager.GetString("lblMATVAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CK cầm cố.
    '''</summary>
    Friend Shared ReadOnly Property lblMortage() As String
        Get
            Return ResourceManager.GetString("lblMortage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TL cảnh báo(%).
    '''</summary>
    Friend Shared ReadOnly Property lblMRATE() As String
        Get
            Return ResourceManager.GetString("lblMRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chênh lệch Deal TL/Deal mới.
    '''</summary>
    Friend Shared ReadOnly Property lblNETBALANCE() As String
        Get
            Return ResourceManager.GetString("lblNETBALANCE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã SP Deal Tlý.
    '''</summary>
    Friend Shared ReadOnly Property lblOLDACTYPE() As String
        Get
            Return ResourceManager.GetString("lblOLDACTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số hiệu Deal thanh lý.
    '''</summary>
    Friend Shared ReadOnly Property lblOLDDEALNO() As String
        Get
            Return ResourceManager.GetString("lblOLDDEALNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to KL có thể thanh lý.
    '''</summary>
    Friend Shared ReadOnly Property lblOLDDFQTTY() As String
        Get
            Return ResourceManager.GetString("lblOLDDFQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TL vay theo rổ Deal Tlý.
    '''</summary>
    Friend Shared ReadOnly Property lblOLDDFRATE() As String
        Get
            Return ResourceManager.GetString("lblOLDDFRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sức mua.
    '''</summary>
    Friend Shared ReadOnly Property lblPurchasingPower() As String
        Get
            Return ResourceManager.GetString("lblPurchasingPower", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số lượng.
    '''</summary>
    Friend Shared ReadOnly Property lblQuantity() As String
        Get
            Return ResourceManager.GetString("lblQuantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GD Gốc.
    '''</summary>
    Friend Shared ReadOnly Property lblREF() As String
        Get
            Return ResourceManager.GetString("lblREF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá cơ bản.
    '''</summary>
    Friend Shared ReadOnly Property lblRefPrice() As String
        Get
            Return ResourceManager.GetString("lblRefPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tham chiếu.
    '''</summary>
    Friend Shared ReadOnly Property lblRefSide() As String
        Get
            Return ResourceManager.GetString("lblRefSide", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bảo lãnh trả.
    '''</summary>
    Friend Shared ReadOnly Property lblREMAINADVLINE() As String
        Get
            Return ResourceManager.GetString("lblREMAINADVLINE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền trả.
    '''</summary>
    Friend Shared ReadOnly Property lblREMAINBAL() As String
        Get
            Return ResourceManager.GetString("lblREMAINBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to KL chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property lblSEBalance() As String
        Get
            Return ResourceManager.GetString("lblSEBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã CK.
    '''</summary>
    Friend Shared ReadOnly Property lblSymbol() As String
        Get
            Return ResourceManager.GetString("lblSymbol", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng GT.
    '''</summary>
    Friend Shared ReadOnly Property lblTOLAMT() As String
        Get
            Return ResourceManager.GetString("lblTOLAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng.
    '''</summary>
    Friend Shared ReadOnly Property lblTotalAmout() As String
        Get
            Return ResourceManager.GetString("lblTotalAmout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá xử lý.
    '''</summary>
    Friend Shared ReadOnly Property lblTRIGPRICE() As String
        Get
            Return ResourceManager.GetString("lblTRIGPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiền cho vay không được vượt quá số tiền cho vay tối đa !.
    '''</summary>
    Friend Shared ReadOnly Property MAXDFOPTION() As String
        Get
            Return ResourceManager.GetString("MAXDFOPTION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư khả dụng.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_BALDEFOVD() As String
        Get
            Return ResourceManager.GetString("MEMBER_BALDEFOVD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá tham chiếu.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_BASICPRICE() As String
        Get
            Return ResourceManager.GetString("MEMBER_BASICPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã SK quyền.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_CAMASTID() As String
        Get
            Return ResourceManager.GetString("MEMBER_CAMASTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá vốn.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_COSTPRICE() As String
        Get
            Return ResourceManager.GetString("MEMBER_COSTPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã khách hàng.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_CUSTID() As String
        Get
            Return ResourceManager.GetString("MEMBER_CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày ĐKQM cuối cùng.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_DUEDATE() As String
        Get
            Return ResourceManager.GetString("MEMBER_DUEDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên khách hàng.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_FULLNAME() As String
        Get
            Return ResourceManager.GetString("MEMBER_FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số chứng thư.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDCODE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cầm cố.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_MORTAGE() As String
        Get
            Return ResourceManager.GetString("MEMBER_MORTAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá mua.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_PRICE() As String
        Get
            Return ResourceManager.GetString("MEMBER_PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số lượng.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_QTTY() As String
        Get
            Return ResourceManager.GetString("MEMBER_QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Địa chỉ.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REF() As String
        Get
            Return ResourceManager.GetString("MEMBER_REF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày chốt DS.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REPORTDATE() As String
        Get
            Return ResourceManager.GetString("MEMBER_REPORTDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_SYMBOL() As String
        Get
            Return ResourceManager.GetString("MEMBER_SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TRADE() As String
        Get
            Return ResourceManager.GetString("MEMBER_TRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kiểu ủy quyền.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYP() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loại.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYPENAME() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYPENAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trong trường hợp Thanh lý tái ký thì Khối lượng tái ký không được lớn hơn khối lượng thanh lý !.
    '''</summary>
    Friend Shared ReadOnly Property NEWQTTYABOVEOLDQTTY() As String
        Get
            Return ResourceManager.GetString("NEWQTTYABOVEOLDQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản thường không được làm margin loan!.
    '''</summary>
    Friend Shared ReadOnly Property NOMAL_CANNOT_MAKE_ML() As String
        Get
            Return ResourceManager.GetString("NOMAL_CANNOT_MAKE_ML", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng số dư khả dụng và bảo lãnh không đủ để trả cho khoản chênh lệch giữa Deal thanh lý và deal mới !.
    '''</summary>
    Friend Shared ReadOnly Property NOTENOUGHMONEY() As String
        Get
            Return ResourceManager.GetString("NOTENOUGHMONEY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trị trường số không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property NUMBER_IS_INVALID() As String
        Get
            Return ResourceManager.GetString("NUMBER_IS_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khác.
    '''</summary>
    Friend Shared ReadOnly Property OTHERS() As String
        Get
            Return ResourceManager.GetString("OTHERS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường giá phải là số dương !.
    '''</summary>
    Friend Shared ReadOnly Property PRICEISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("PRICEISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường số lượng phải là số !.
    '''</summary>
    Friend Shared ReadOnly Property QTTYISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("QTTYISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chứng khoán đã được thêm vào trong deal tổng.
    '''</summary>
    Friend Shared ReadOnly Property QTTYSYMBOL() As String
        Get
            Return ResourceManager.GetString("QTTYSYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trường tỉ lệ phải là số !.
    '''</summary>
    Friend Shared ReadOnly Property RATENONUMBER() As String
        Get
            Return ResourceManager.GetString("RATENONUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bạn có hủy giao dịch không?.
    '''</summary>
    Friend Shared ReadOnly Property Reject() As String
        Get
            Return ResourceManager.GetString("Reject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giao dịch thành công.
    '''</summary>
    Friend Shared ReadOnly Property SuccessConfirm() As String
        Get
            Return ResourceManager.GetString("SuccessConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hủy giao dịch thành công.
    '''</summary>
    Friend Shared ReadOnly Property SuccessReject() As String
        Get
            Return ResourceManager.GetString("SuccessReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng cầm cố lớn hơn khối lượng có thể giao dịch hiện tại !.
    '''</summary>
    Friend Shared ReadOnly Property TRADEQTTYLESSQTTY() As String
        Get
            Return ResourceManager.GetString("TRADEQTTYLESSQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá trigger phải bé hơn hoặc bằng giá tham chiếu.
    '''</summary>
    Friend Shared ReadOnly Property TRIGGER_MUST_BE_HIGHT_THAN_REFPRICE() As String
        Get
            Return ResourceManager.GetString("TRIGGER_MUST_BE_HIGHT_THAN_REFPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá xử lý không được lớn hơn giá tham chiếu!.
    '''</summary>
    Friend Shared ReadOnly Property TRIGGERPRICE_OVER_REFPRICE() As String
        Get
            Return ResourceManager.GetString("TRIGGERPRICE_OVER_REFPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày GD.
    '''</summary>
    Friend Shared ReadOnly Property TXDATE() As String
        Get
            Return ResourceManager.GetString("TXDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Diễn giải của giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property txtDescription() As String
        Get
            Return ResourceManager.GetString("txtDescription", resourceCulture)
        End Get
    End Property
End Class
