'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmDefineRisk_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmDefineRisk-EN", GetType(frmDefineRisk_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type name.
    '''</summary>
    Friend Shared ReadOnly Property ACNAME() As String
        Get
            Return ResourceManager.GetString("ACNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Product type.
    '''</summary>
    Friend Shared ReadOnly Property ACTYPE() As String
        Get
            Return ResourceManager.GetString("ACTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add new securities ticksize successfully!.
    '''</summary>
    Friend Shared ReadOnly Property AddnewSuccessful() As String
        Get
            Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance max.
    '''</summary>
    Friend Shared ReadOnly Property ADVANCEDLIMITMAX() As String
        Get
            Return ResourceManager.GetString("ADVANCEDLIMITMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance min.
    '''</summary>
    Friend Shared ReadOnly Property ADVANCEDLIMITMIN() As String
        Get
            Return ResourceManager.GetString("ADVANCEDLIMITMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AdvancedLimit.
    '''</summary>
    Friend Shared ReadOnly Property ADVANCELINE() As String
        Get
            Return ResourceManager.GetString("ADVANCELINE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ask price.
    '''</summary>
    Friend Shared ReadOnly Property ASKPRICE() As String
        Get
            Return ResourceManager.GetString("ASKPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bid price.
    '''</summary>
    Friend Shared ReadOnly Property BIDPRICE() As String
        Get
            Return ResourceManager.GetString("BIDPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Secured Ratio.
    '''</summary>
    Friend Shared ReadOnly Property BRATIO() As String
        Get
            Return ResourceManager.GetString("BRATIO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Add new.
    '''</summary>
    Friend Shared ReadOnly Property btnADD() As String
        Get
            Return ResourceManager.GetString("btnADD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Apply.
    '''</summary>
    Friend Shared ReadOnly Property btnApply() As String
        Get
            Return ResourceManager.GetString("btnApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property btnCLOSE() As String
        Get
            Return ResourceManager.GetString("btnCLOSE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property btnDELETE() As String
        Get
            Return ResourceManager.GetString("btnDELETE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Edit.
    '''</summary>
    Friend Shared ReadOnly Property btnEDIT() As String
        Get
            Return ResourceManager.GetString("btnEDIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Export.
    '''</summary>
    Friend Shared ReadOnly Property btnExport() As String
        Get
            Return ResourceManager.GetString("btnExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Import.
    '''</summary>
    Friend Shared ReadOnly Property btnIMPORT() As String
        Get
            Return ResourceManager.GetString("btnIMPORT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;View.
    '''</summary>
    Friend Shared ReadOnly Property btnVIEW() As String
        Get
            Return ResourceManager.GetString("btnVIEW", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to IntRate.
    '''</summary>
    Friend Shared ReadOnly Property CRINTRATE() As String
        Get
            Return ResourceManager.GetString("CRINTRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to delete this data row?.
    '''</summary>
    Friend Shared ReadOnly Property DelConfirm() As String
        Get
            Return ResourceManager.GetString("DelConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Depository Fee.
    '''</summary>
    Friend Shared ReadOnly Property DEPORATE() As String
        Get
            Return ResourceManager.GetString("DEPORATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit securities ticksize information successfully!.
    '''</summary>
    Friend Shared ReadOnly Property EditSuccessful() As String
        Get
            Return ResourceManager.GetString("EditSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Free rate.
    '''</summary>
    Friend Shared ReadOnly Property FEERATE() As String
        Get
            Return ResourceManager.GetString("FEERATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floor limit.
    '''</summary>
    Friend Shared ReadOnly Property FLOORLIMIT() As String
        Get
            Return ResourceManager.GetString("FLOORLIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Risk paramater.
    '''</summary>
    Friend Shared ReadOnly Property frmDefineRisk() As String
        Get
            Return ResourceManager.GetString("frmDefineRisk", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rate managerment.
    '''</summary>
    Friend Shared ReadOnly Property frmIRRATE() As String
        Get
            Return ResourceManager.GetString("frmIRRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Risk managerment.
    '''</summary>
    Friend Shared ReadOnly Property frmRISK() As String
        Get
            Return ResourceManager.GetString("frmRISK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System management.
    '''</summary>
    Friend Shared ReadOnly Property frmSYSVAR() As String
        Get
            Return ResourceManager.GetString("frmSYSVAR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ticksize information:.
    '''</summary>
    Friend Shared ReadOnly Property grbTicksizeInfo() As String
        Get
            Return ResourceManager.GetString("grbTicksizeInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dialog initiation is failed!.
    '''</summary>
    Friend Shared ReadOnly Property InitDialogFailed() As String
        Get
            Return ResourceManager.GetString("InitDialogFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System management..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Risk ICCF information..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption0() As String
        Get
            Return ResourceManager.GetString("lblCaption0", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add new securities ticksize..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption1() As String
        Get
            Return ResourceManager.GetString("lblCaption1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit securities ticksize information..
    '''</summary>
    Friend Shared ReadOnly Property lblCaption2() As String
        Get
            Return ResourceManager.GetString("lblCaption2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Business module.
    '''</summary>
    Friend Shared ReadOnly Property lblModule() As String
        Get
            Return ResourceManager.GetString("lblModule", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The field [@] should not be empty!.
    '''</summary>
    Friend Shared ReadOnly Property Mandatory() As String
        Get
            Return ResourceManager.GetString("Mandatory", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Margin max.
    '''</summary>
    Friend Shared ReadOnly Property MARGINLIMITMAX() As String
        Get
            Return ResourceManager.GetString("MARGINLIMITMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Margin min.
    '''</summary>
    Friend Shared ReadOnly Property MARGINLIMITMIN() As String
        Get
            Return ResourceManager.GetString("MARGINLIMITMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MarginLimit.
    '''</summary>
    Friend Shared ReadOnly Property MARGINLINE() As String
        Get
            Return ResourceManager.GetString("MARGINLINE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Misc Fee.
    '''</summary>
    Friend Shared ReadOnly Property MISCRATE() As String
        Get
            Return ResourceManager.GetString("MISCRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mortage max.
    '''</summary>
    Friend Shared ReadOnly Property MORTAGERATIOMAX() As String
        Get
            Return ResourceManager.GetString("MORTAGERATIOMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mortage min.
    '''</summary>
    Friend Shared ReadOnly Property MORTAGERATIOMIN() As String
        Get
            Return ResourceManager.GetString("MORTAGERATIOMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The field [@] data type should be numeric!.
    '''</summary>
    Friend Shared ReadOnly Property NumericDataType() As String
        Get
            Return ResourceManager.GetString("NumericDataType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order Rate.
    '''</summary>
    Friend Shared ReadOnly Property ODRATE() As String
        Get
            Return ResourceManager.GetString("ODRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to OnlineLimit.
    '''</summary>
    Friend Shared ReadOnly Property ONLINELIMIT() As String
        Get
            Return ResourceManager.GetString("ONLINELIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Online max.
    '''</summary>
    Friend Shared ReadOnly Property ONLINELIMITMAX() As String
        Get
            Return ResourceManager.GetString("ONLINELIMITMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Online min.
    '''</summary>
    Friend Shared ReadOnly Property ONLINELIMITMIN() As String
        Get
            Return ResourceManager.GetString("ONLINELIMITMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Repo max.
    '''</summary>
    Friend Shared ReadOnly Property REPOLIMITMAX() As String
        Get
            Return ResourceManager.GetString("REPOLIMITMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Repo min.
    '''</summary>
    Friend Shared ReadOnly Property REPOLIMITMIN() As String
        Get
            Return ResourceManager.GetString("REPOLIMITMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RepoLimit.
    '''</summary>
    Friend Shared ReadOnly Property REPOLINE() As String
        Get
            Return ResourceManager.GetString("REPOLINE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Saving failed!.
    '''</summary>
    Friend Shared ReadOnly Property SavingFailed() As String
        Get
            Return ResourceManager.GetString("SavingFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Secured max.
    '''</summary>
    Friend Shared ReadOnly Property SECUREDRATIOMAX() As String
        Get
            Return ResourceManager.GetString("SECUREDRATIOMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Secured min.
    '''</summary>
    Friend Shared ReadOnly Property SECUREDRATIOMIN() As String
        Get
            Return ResourceManager.GetString("SECUREDRATIOMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol.
    '''</summary>
    Friend Shared ReadOnly Property SYMBOL() As String
        Get
            Return ResourceManager.GetString("SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ICCF Information.
    '''</summary>
    Friend Shared ReadOnly Property TabICCF() As String
        Get
            Return ResourceManager.GetString("TabICCF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floating rate.
    '''</summary>
    Friend Shared ReadOnly Property TabIRRATE() As String
        Get
            Return ResourceManager.GetString("TabIRRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to cash investment.
    '''</summary>
    Friend Shared ReadOnly Property tablCI() As String
        Get
            Return ResourceManager.GetString("tablCI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order.
    '''</summary>
    Friend Shared ReadOnly Property tablOD() As String
        Get
            Return ResourceManager.GetString("tablOD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Securities margin.
    '''</summary>
    Friend Shared ReadOnly Property TabMarginSec() As String
        Get
            Return ResourceManager.GetString("TabMarginSec", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Product parameters.
    '''</summary>
    Friend Shared ReadOnly Property tabPRODUCT() As String
        Get
            Return ResourceManager.GetString("tabPRODUCT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System Securities Risk.
    '''</summary>
    Friend Shared ReadOnly Property TabSERISK() As String
        Get
            Return ResourceManager.GetString("TabSERISK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to System Common.
    '''</summary>
    Friend Shared ReadOnly Property TabSYSVAR() As String
        Get
            Return ResourceManager.GetString("TabSYSVAR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TeleLimit.
    '''</summary>
    Friend Shared ReadOnly Property TELELIMIT() As String
        Get
            Return ResourceManager.GetString("TELELIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tele limit max.
    '''</summary>
    Friend Shared ReadOnly Property TELELIMITMAX() As String
        Get
            Return ResourceManager.GetString("TELELIMITMAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tele limit min.
    '''</summary>
    Friend Shared ReadOnly Property TELELIMITMIN() As String
        Get
            Return ResourceManager.GetString("TELELIMITMIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Total trade.
    '''</summary>
    Friend Shared ReadOnly Property TOTALTRADE() As String
        Get
            Return ResourceManager.GetString("TOTALTRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trade limit.
    '''</summary>
    Friend Shared ReadOnly Property TRADELIMIT() As String
        Get
            Return ResourceManager.GetString("TRADELIMIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trading Fee.
    '''</summary>
    Friend Shared ReadOnly Property TRADERATE() As String
        Get
            Return ResourceManager.GetString("TRADERATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trade unit:.
    '''</summary>
    Friend Shared ReadOnly Property TRADEUNIT() As String
        Get
            Return ResourceManager.GetString("TRADEUNIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type name.
    '''</summary>
    Friend Shared ReadOnly Property TYPENAME() As String
        Get
            Return ResourceManager.GetString("TYPENAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VatRate.
    '''</summary>
    Friend Shared ReadOnly Property VATRATE() As String
        Get
            Return ResourceManager.GetString("VATRATE", resourceCulture)
        End Get
    End Property
End Class
