'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmGroupOrderPT_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmGroupOrderPT-EN", GetType(frmGroupOrderPT_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to approve?.
    '''</summary>
    Friend Shared ReadOnly Property ApproveConfirm() As String
        Get
            Return ResourceManager.GetString("ApproveConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approved Successful.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Adjust.
    '''</summary>
    Friend Shared ReadOnly Property btnAdjust() As String
        Get
            Return ResourceManager.GetString("btnAdjust", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Amend.
    '''</summary>
    Friend Shared ReadOnly Property btnAmend() As String
        Get
            Return ResourceManager.GetString("btnAmend", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A&amp;pprove.
    '''</summary>
    Friend Shared ReadOnly Property btnApprove() As String
        Get
            Return ResourceManager.GetString("btnApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCANCEL() As String
        Get
            Return ResourceManager.GetString("btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCanDel() As String
        Get
            Return ResourceManager.GetString("btnCanDel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete.
    '''</summary>
    Friend Shared ReadOnly Property btnDelete() As String
        Get
            Return ResourceManager.GetString("btnDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Down.
    '''</summary>
    Friend Shared ReadOnly Property btnDOWN() As String
        Get
            Return ResourceManager.GetString("btnDOWN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Exit.
    '''</summary>
    Friend Shared ReadOnly Property btnExit() As String
        Get
            Return ResourceManager.GetString("btnExit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &gt;.
    '''</summary>
    Friend Shared ReadOnly Property btnNext() As String
        Get
            Return ResourceManager.GetString("btnNext", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;.
    '''</summary>
    Friend Shared ReadOnly Property btnPrev() As String
        Get
            Return ResourceManager.GetString("btnPrev", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Re&amp;fuse.
    '''</summary>
    Friend Shared ReadOnly Property btnRefuse() As String
        Get
            Return ResourceManager.GetString("btnRefuse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Reject.
    '''</summary>
    Friend Shared ReadOnly Property btnReject() As String
        Get
            Return ResourceManager.GetString("btnReject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Up.
    '''</summary>
    Friend Shared ReadOnly Property btnUP() As String
        Get
            Return ResourceManager.GetString("btnUP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ceiling price is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CEILINGINVALID() As String
        Get
            Return ResourceManager.GetString("CEILINGINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ceiling price:.
    '''</summary>
    Friend Shared ReadOnly Property CEILINGPRICE() As String
        Get
            Return ResourceManager.GetString("CEILINGPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to All?.
    '''</summary>
    Friend Shared ReadOnly Property chkAllorNone() As String
        Get
            Return ResourceManager.GetString("chkAllorNone", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order repo.
    '''</summary>
    Friend Shared ReadOnly Property chkPTRepo() As String
        Get
            Return ResourceManager.GetString("chkPTRepo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TBS?.
    '''</summary>
    Friend Shared ReadOnly Property chkTBS() As String
        Get
            Return ResourceManager.GetString("chkTBS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settlement cycle is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CLEARINGDAYINVALID() As String
        Get
            Return ResourceManager.GetString("CLEARINGDAYINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Client ID.
    '''</summary>
    Friend Shared ReadOnly Property CLIENTID() As String
        Get
            Return ResourceManager.GetString("CLIENTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contract is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CONTRACTINVALID() As String
        Get
            Return ResourceManager.GetString("CONTRACTINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contra firm .
    '''</summary>
    Friend Shared ReadOnly Property CONTRAFIRM() As String
        Get
            Return ResourceManager.GetString("CONTRAFIRM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code:.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adv order does not send to current custody member!.
    '''</summary>
    Friend Shared ReadOnly Property DELIVERTO_OTHER() As String
        Get
            Return ResourceManager.GetString("DELIVERTO_OTHER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng phân bổ không hợp lệ!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_ADDQTTY_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_ADDQTTY_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng đặt bán lớn hơn khối lượng có thể bán!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_ADDQTTY_OVER_AVAILABLE() As String
        Get
            Return ResourceManager.GetString("ERR_ADDQTTY_OVER_AVAILABLE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear day is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CLEARINGDAY_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_CLEARINGDAY_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid securities information!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CODEID_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_CODEID_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CUSTODY_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_CUSTODY_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expired date is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_EXPIREDDATE_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_EXPIREDDATE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This field can not be null!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_FIELD_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_FIELD_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid account number!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INV_NUMBER() As String
        Get
            Return ResourceManager.GetString("ERR_INV_NUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid account number!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_ACCNUM() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_ACCNUM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You can not make pouthrought order with market price !!!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_PTORDER() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_PTORDER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid correction quantity!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_QTTY() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity can&apos;t less then {0} when match type is Putthrought!!!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_QTTY1000() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_QTTY1000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Stock amount is invalid!!!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INVALID_STOCK_NUM() As String
        Get
            Return ResourceManager.GetString("ERR_INVALID_STOCK_NUM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Member of this Issuers !!!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_ISSUER_MEMBER() As String
        Get
            Return ResourceManager.GetString("ERR_ISSUER_MEMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amendment Balance: {0} over original balance.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NOT_ABL() As String
        Get
            Return ResourceManager.GetString("ERR_NOT_ABL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI Balance: {0} not enought to buy.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NOT_ECI() As String
        Get
            Return ResourceManager.GetString("ERR_NOT_ECI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mortage Balance: {0} not enought to sell.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NOT_EMT() As String
        Get
            Return ResourceManager.GetString("ERR_NOT_EMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not enough securities!!!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NOT_ENOUGH_SECURITIES() As String
        Get
            Return ResourceManager.GetString("ERR_NOT_ENOUGH_SECURITIES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE Balance: {0} not enought to sell.
    '''</summary>
    Friend Shared ReadOnly Property ERR_NOT_ESE() As String
        Get
            Return ResourceManager.GetString("ERR_NOT_ESE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Product type not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_PROD_TYPE() As String
        Get
            Return ResourceManager.GetString("ERR_PROD_TYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Product type not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_PRODUCTTYPE_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_PRODUCTTYPE_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid securities information!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_SEC_INFO() As String
        Get
            Return ResourceManager.GetString("ERR_SEC_INFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Securities halted!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_SHALT() As String
        Get
            Return ResourceManager.GetString("ERR_SHALT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Securities halted with nomal trasaction!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_STOCK_HALT() As String
        Get
            Return ResourceManager.GetString("ERR_STOCK_HALT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Securities halted with put though trasaction!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_STOCK_HALT_PT() As String
        Get
            Return ResourceManager.GetString("ERR_STOCK_HALT_PT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Stock fields can not be null!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_STOCK_NOT_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_STOCK_NOT_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floor price is invalid.
    '''</summary>
    Friend Shared ReadOnly Property FLOORINVALID() As String
        Get
            Return ResourceManager.GetString("FLOORINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floor price:.
    '''</summary>
    Friend Shared ReadOnly Property FLOORPRICE() As String
        Get
            Return ResourceManager.GetString("FLOORPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Authorize information management.
    '''</summary>
    Friend Shared ReadOnly Property frm_CFAUTH() As String
        Get
            Return ResourceManager.GetString("frm_CFAUTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer information management.
    '''</summary>
    Friend Shared ReadOnly Property frm_CFMAST() As String
        Get
            Return ResourceManager.GetString("frm_CFMAST", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fullname:.
    '''</summary>
    Friend Shared ReadOnly Property FULLNAME() As String
        Get
            Return ResourceManager.GetString("FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Identification:.
    '''</summary>
    Friend Shared ReadOnly Property IDCODE() As String
        Get
            Return ResourceManager.GetString("IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol invalid!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_CODEID() As String
        Get
            Return ResourceManager.GetString("INVALID_CODEID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custodycode invalid!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("INVALID_CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Exectype!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_EXECTYPE() As String
        Get
            Return ResourceManager.GetString("INVALID_EXECTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid firm!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_FIRM() As String
        Get
            Return ResourceManager.GetString("INVALID_FIRM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order qtty invalid.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_ORDERQTTY() As String
        Get
            Return ResourceManager.GetString("INVALID_ORDERQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid RefOrderID!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_REFORDERID() As String
        Get
            Return ResourceManager.GetString("INVALID_REFORDERID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref Order status invalid!.
    '''</summary>
    Friend Shared ReadOnly Property INVALID_STATUS() As String
        Get
            Return ResourceManager.GetString("INVALID_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to He/she is member of this issuer. Do you want continue place order ?.
    '''</summary>
    Friend Shared ReadOnly Property ISISSUER() As String
        Get
            Return ResourceManager.GetString("ISISSUER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AdvIdRef.
    '''</summary>
    Friend Shared ReadOnly Property lblAdvIdRef() As String
        Get
            Return ResourceManager.GetString("lblAdvIdRef", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code:.
    '''</summary>
    Friend Shared ReadOnly Property lblAFACCTNO() As String
        Get
            Return ResourceManager.GetString("lblAFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Buy Custody code:.
    '''</summary>
    Friend Shared ReadOnly Property lblBuyCustody() As String
        Get
            Return ResourceManager.GetString("lblBuyCustody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Calendar:.
    '''</summary>
    Friend Shared ReadOnly Property lblCalendar() As String
        Get
            Return ResourceManager.GetString("lblCalendar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance payment.
    '''</summary>
    Friend Shared ReadOnly Property lblCIAdvance() As String
        Get
            Return ResourceManager.GetString("lblCIAdvance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Available balance:.
    '''</summary>
    Friend Shared ReadOnly Property lblCIBalance() As String
        Get
            Return ResourceManager.GetString("lblCIBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settlement cycle:.
    '''</summary>
    Friend Shared ReadOnly Property lblClearingDay() As String
        Get
            Return ResourceManager.GetString("lblClearingDay", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ClientID.
    '''</summary>
    Friend Shared ReadOnly Property lblClientID() As String
        Get
            Return ResourceManager.GetString("lblClientID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Consultant:.
    '''</summary>
    Friend Shared ReadOnly Property lblConsultant() As String
        Get
            Return ResourceManager.GetString("lblConsultant", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contrafirm.
    '''</summary>
    Friend Shared ReadOnly Property lblContrafirm() As String
        Get
            Return ResourceManager.GetString("lblContrafirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description:.
    '''</summary>
    Friend Shared ReadOnly Property lblDescription() As String
        Get
            Return ResourceManager.GetString("lblDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Exec type:.
    '''</summary>
    Friend Shared ReadOnly Property lblExecType() As String
        Get
            Return ResourceManager.GetString("lblExecType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expired date:.
    '''</summary>
    Friend Shared ReadOnly Property lblExpiredDate() As String
        Get
            Return ResourceManager.GetString("lblExpiredDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ex date:.
    '''</summary>
    Friend Shared ReadOnly Property lblEXPTDATE() As String
        Get
            Return ResourceManager.GetString("lblEXPTDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price 2:.
    '''</summary>
    Friend Shared ReadOnly Property lblEXPTPRICE() As String
        Get
            Return ResourceManager.GetString("lblEXPTPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Limit price:.
    '''</summary>
    Friend Shared ReadOnly Property lblLimitPrice() As String
        Get
            Return ResourceManager.GetString("lblLimitPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Match type:.
    '''</summary>
    Friend Shared ReadOnly Property lblMatchType() As String
        Get
            Return ResourceManager.GetString("lblMatchType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Price type:.
    '''</summary>
    Friend Shared ReadOnly Property lblPriceType() As String
        Get
            Return ResourceManager.GetString("lblPriceType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Quantity:.
    '''</summary>
    Friend Shared ReadOnly Property lblQuantity() As String
        Get
            Return ResourceManager.GetString("lblQuantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reference:.
    '''</summary>
    Friend Shared ReadOnly Property lblReference() As String
        Get
            Return ResourceManager.GetString("lblReference", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref orderid:.
    '''</summary>
    Friend Shared ReadOnly Property lblREFORDERID() As String
        Get
            Return ResourceManager.GetString("lblREFORDERID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE balance:.
    '''</summary>
    Friend Shared ReadOnly Property lblSEBalance() As String
        Get
            Return ResourceManager.GetString("lblSEBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sell Custody code:.
    '''</summary>
    Friend Shared ReadOnly Property lblSellCustody() As String
        Get
            Return ResourceManager.GetString("lblSellCustody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Stop price:.
    '''</summary>
    Friend Shared ReadOnly Property lblStopPrice() As String
        Get
            Return ResourceManager.GetString("lblStopPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Symbol:.
    '''</summary>
    Friend Shared ReadOnly Property lblSymbol() As String
        Get
            Return ResourceManager.GetString("lblSymbol", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Time type:.
    '''</summary>
    Friend Shared ReadOnly Property lblTimeType() As String
        Get
            Return ResourceManager.GetString("lblTimeType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Total.
    '''</summary>
    Friend Shared ReadOnly Property lblTotalAmout() As String
        Get
            Return ResourceManager.GetString("lblTotalAmout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TraderID.
    '''</summary>
    Friend Shared ReadOnly Property lblTraderid() As String
        Get
            Return ResourceManager.GetString("lblTraderid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to By Channel:.
    '''</summary>
    Friend Shared ReadOnly Property lblVia() As String
        Get
            Return ResourceManager.GetString("lblVia", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Voucher:.
    '''</summary>
    Friend Shared ReadOnly Property lblVoucher() As String
        Get
            Return ResourceManager.GetString("lblVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sub account.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_AFACCTNO() As String
        Get
            Return ResourceManager.GetString("MEMBER_AFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Allocate Qtty.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_AlLOCQTTY() As String
        Get
            Return ResourceManager.GetString("MEMBER_AlLOCQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref Price.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_BASICPRICE() As String
        Get
            Return ResourceManager.GetString("MEMBER_BASICPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cost Price.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_COSTPRICE() As String
        Get
            Return ResourceManager.GetString("MEMBER_COSTPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CustID.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_CUSTID() As String
        Get
            Return ResourceManager.GetString("MEMBER_CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fullname.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_FULLNAME() As String
        Get
            Return ResourceManager.GetString("MEMBER_FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Idcode.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDCODE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mortage.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_MORTAGE() As String
        Get
            Return ResourceManager.GetString("MEMBER_MORTAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ORDERID.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_ORDERID() As String
        Get
            Return ResourceManager.GetString("MEMBER_ORDERID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to OrderNum.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_ORDNUM() As String
        Get
            Return ResourceManager.GetString("MEMBER_ORDNUM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_QTTY() As String
        Get
            Return ResourceManager.GetString("MEMBER_QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REF() As String
        Get
            Return ResourceManager.GetString("MEMBER_REF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref ID.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REFID() As String
        Get
            Return ResourceManager.GetString("MEMBER_REFID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Status.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_STATUS() As String
        Get
            Return ResourceManager.GetString("MEMBER_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_SYMBOL() As String
        Get
            Return ResourceManager.GetString("MEMBER_SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trading.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TRADE() As String
        Get
            Return ResourceManager.GetString("MEMBER_TRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYP() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYPE() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid custody code.
    '''</summary>
    Friend Shared ReadOnly Property msgCFNOTFOUND() As String
        Get
            Return ResourceManager.GetString("msgCFNOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed max buy qtty.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER__SYMBOL_BUYAMT() As String
        Get
            Return ResourceManager.GetString("msgDEALER__SYMBOL_BUYAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Admin dealer do not allowed to place orders.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_ADMIN_NOTPLO() As String
        Get
            Return ResourceManager.GetString("msgDEALER_ADMIN_NOTPLO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to not comply with PI controlling rule.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_CHECK_FAILED() As String
        Get
            Return ResourceManager.GetString("msgDEALER_CHECK_FAILED", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed company NAV.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_COMPANY_MAXNAV() As String
        Get
            Return ResourceManager.GetString("msgDEALER_COMPANY_MAXNAV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Over max qtty!.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_COMPANY_MAXQTTYORDER() As String
        Get
            Return ResourceManager.GetString("msgDEALER_COMPANY_MAXQTTYORDER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed group NAV.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_GROUP_MAXNAV() As String
        Get
            Return ResourceManager.GetString("msgDEALER_GROUP_MAXNAV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dealer leader do not allowed to place orders.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_LEADER_NOTPLO() As String
        Get
            Return ResourceManager.GetString("msgDEALER_LEADER_NOTPLO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed buy price range.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_DELTA_BUYING_PRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_DELTA_BUYING_PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed price range.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_DELTA_SELLING_PRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_DELTA_SELLING_PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed buy price.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_MAX_BUYING_PRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_MAX_BUYING_PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid price sell.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_MIN_SELLING_PRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_MIN_SELLING_PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Beyond portfolio.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_SYS_CURRENT_NAV_ALL() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_SYS_CURRENT_NAV_ALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed max order qtty .
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_SYS_MAX_QTTY_PER_ORDER() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_SYS_MAX_QTTY_PER_ORDER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed max qtty.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_OVER_TOTAL_QTTY() As String
        Get
            Return ResourceManager.GetString("msgDEALER_OVER_TOTAL_QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed max buy price.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_BUYPRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_BUYPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol halt.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_CANNOT_TRADE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_CANNOT_TRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to exceed max owning quantity.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_MAXAVL() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_MAXAVL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed min owning quantity.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_MINAVL() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_MINAVL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed max sell price.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_SELLAMT() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_SELLAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed min sell price.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_SYMBOL_SELLPRICE() As String
        Get
            Return ResourceManager.GetString("msgDEALER_SYMBOL_SELLPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dealer leader do not allowed to place orders.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_TRADER_CANNOT_PLACE_ORDER() As String
        Get
            Return ResourceManager.GetString("msgDEALER_TRADER_CANNOT_PLACE_ORDER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exceed officer NAV.
    '''</summary>
    Friend Shared ReadOnly Property msgDEALER_TRADER_MAXNAV() As String
        Get
            Return ResourceManager.GetString("msgDEALER_TRADER_MAXNAV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Avaiable buy amount.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_AVLBUYAMT() As String
        Get
            Return ResourceManager.GetString("POLICY_AVLBUYAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Avl Qtty.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_AVLQTTY() As String
        Get
            Return ResourceManager.GetString("POLICY_AVLQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Avaiable sell amount.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_AVLSELLAMT() As String
        Get
            Return ResourceManager.GetString("POLICY_AVLSELLAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Avaiable buying amount.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_BUYAMT() As String
        Get
            Return ResourceManager.GetString("POLICY_BUYAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delta Buy.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_DELTABPRC() As String
        Get
            Return ResourceManager.GetString("POLICY_DELTABPRC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delta Sell.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_DELTASPRC() As String
        Get
            Return ResourceManager.GetString("POLICY_DELTASPRC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_FRDATE() As String
        Get
            Return ResourceManager.GetString("POLICY_FRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Leader.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_LEADER() As String
        Get
            Return ResourceManager.GetString("POLICY_LEADER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max Buy.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MAXALLBUY() As String
        Get
            Return ResourceManager.GetString("POLICY_MAXALLBUY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max Sell.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MAXALLSELL() As String
        Get
            Return ResourceManager.GetString("POLICY_MAXALLSELL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max avl Qtty.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MAXAVLBAL() As String
        Get
            Return ResourceManager.GetString("POLICY_MAXAVLBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max Buy price.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MAXBPRICE() As String
        Get
            Return ResourceManager.GetString("POLICY_MAXBPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max NAV.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MAXNAV() As String
        Get
            Return ResourceManager.GetString("POLICY_MAXNAV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min Avl Balanace.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MINAVLBAL() As String
        Get
            Return ResourceManager.GetString("POLICY_MINAVLBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min Sell price.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_MINSPRICE() As String
        Get
            Return ResourceManager.GetString("POLICY_MINSPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Avaiable selling amount.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_SELLAMT() As String
        Get
            Return ResourceManager.GetString("POLICY_SELLAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_SYMBOL() As String
        Get
            Return ResourceManager.GetString("POLICY_SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to To date.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_TODATE() As String
        Get
            Return ResourceManager.GetString("POLICY_TODATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Total qtty.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_TOTALQTTY() As String
        Get
            Return ResourceManager.GetString("POLICY_TOTALQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trader.
    '''</summary>
    Friend Shared ReadOnly Property POLICY_TRADER() As String
        Get
            Return ResourceManager.GetString("POLICY_TRADER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price is invalid.
    '''</summary>
    Friend Shared ReadOnly Property PRICEISINVALID() As String
        Get
            Return ResourceManager.GetString("PRICEISINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price should be numeric value.
    '''</summary>
    Friend Shared ReadOnly Property PRICEISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("PRICEISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity should be numeric value.
    '''</summary>
    Friend Shared ReadOnly Property QTTYISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("QTTYISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thỏa thuận 1 firm.
    '''</summary>
    Friend Shared ReadOnly Property rdOneFirm() As String
        Get
            Return ResourceManager.GetString("rdOneFirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thỏa thuận 2 firm.
    '''</summary>
    Friend Shared ReadOnly Property rdTwoFirm() As String
        Get
            Return ResourceManager.GetString("rdTwoFirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref. price:.
    '''</summary>
    Friend Shared ReadOnly Property REFPRICE() As String
        Get
            Return ResourceManager.GetString("REFPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to refuse?.
    '''</summary>
    Friend Shared ReadOnly Property RefuseConfirm() As String
        Get
            Return ResourceManager.GetString("RefuseConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refuse successful!.
    '''</summary>
    Friend Shared ReadOnly Property RefusedSuccessful() As String
        Get
            Return ResourceManager.GetString("RefusedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter your comment!.
    '''</summary>
    Friend Shared ReadOnly Property RejectComment() As String
        Get
            Return ResourceManager.GetString("RejectComment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to reject?.
    '''</summary>
    Friend Shared ReadOnly Property RejectConfirm() As String
        Get
            Return ResourceManager.GetString("RejectConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rerected Successful.
    '''</summary>
    Friend Shared ReadOnly Property RerectedSuccessful() As String
        Get
            Return ResourceManager.GetString("RerectedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Buy and sell same securities in day !!!.
    '''</summary>
    Friend Shared ReadOnly Property TRADE_BUYSELL() As String
        Get
            Return ResourceManager.GetString("TRADE_BUYSELL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lot:.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOT() As String
        Get
            Return ResourceManager.GetString("TRADELOT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity mus greater than {1}!.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOTHAPT() As String
        Get
            Return ResourceManager.GetString("TRADELOTHAPT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity mus greater than {0}!.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOTHOPT() As String
        Get
            Return ResourceManager.GetString("TRADELOTHOPT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tradelot is invalid.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOTINVALID() As String
        Get
            Return ResourceManager.GetString("TRADELOTINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trader ID.
    '''</summary>
    Friend Shared ReadOnly Property TRADERID() As String
        Get
            Return ResourceManager.GetString("TRADERID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unit:.
    '''</summary>
    Friend Shared ReadOnly Property TRADEUNIT() As String
        Get
            Return ResourceManager.GetString("TRADEUNIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Put though group order.
    '''</summary>
    Friend Shared ReadOnly Property TXT_DECRIPTION() As String
        Get
            Return ResourceManager.GetString("TXT_DECRIPTION", resourceCulture)
        End Get
    End Property
End Class
