'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmManualAdvance_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmManualAdvance-EN", GetType(frmManualAdvance_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance receiving amount.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_ADVAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_ADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max advance amount.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_AVLADVAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_AVLADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance fee per month.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_BNKFEEAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_BNKFEEAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance days.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_DAYS() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_DAYS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_DESC() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_DESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Due date.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_DUEDATE() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_DUEDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance fee.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_FEEAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_FEEAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mortage of VSD.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_ISVSD() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_ISVSD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Match date.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_MATCHDATE() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_MATCHDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Real receving amount.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_RCVADVAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_RCVADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT.
    '''</summary>
    Friend Shared ReadOnly Property ADVSCHD_VATAMT() As String
        Get
            Return ResourceManager.GetString("ADVSCHD_VATAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Adjust.
    '''</summary>
    Friend Shared ReadOnly Property btnAdjust() As String
        Get
            Return ResourceManager.GetString("btnAdjust", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apply.
    '''</summary>
    Friend Shared ReadOnly Property btnApply() As String
        Get
            Return ResourceManager.GetString("btnApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Print.
    '''</summary>
    Friend Shared ReadOnly Property btnPRINT() As String
        Get
            Return ResourceManager.GetString("btnPRINT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Continue advance.
    '''</summary>
    Friend Shared ReadOnly Property ConfirmApply() As String
        Get
            Return ResourceManager.GetString("ConfirmApply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transact no. not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_TLTXCD_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_TLTXCD_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance payment.
    '''</summary>
    Friend Shared ReadOnly Property frmManualAdvance() As String
        Get
            Return ResourceManager.GetString("frmManualAdvance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance info.
    '''</summary>
    Friend Shared ReadOnly Property grbAdvInfo() As String
        Get
            Return ResourceManager.GetString("grbAdvInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance schedule.
    '''</summary>
    Friend Shared ReadOnly Property grbAdvSchd() As String
        Get
            Return ResourceManager.GetString("grbAdvSchd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer info.
    '''</summary>
    Friend Shared ReadOnly Property grbCFInfo() As String
        Get
            Return ResourceManager.GetString("grbCFInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid request number.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDADVAMT() As String
        Get
            Return ResourceManager.GetString("INVALIDADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance type invalid.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDAFTYPEADTYPE() As String
        Get
            Return ResourceManager.GetString("INVALIDAFTYPEADTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer info invalid.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDCUSTINFO() As String
        Get
            Return ResourceManager.GetString("INVALIDCUSTINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody Code is Invalid!.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("INVALIDCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Address.
    '''</summary>
    Friend Shared ReadOnly Property lblADDRESS() As String
        Get
            Return ResourceManager.GetString("lblADDRESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance type.
    '''</summary>
    Friend Shared ReadOnly Property lblADTYPE() As String
        Get
            Return ResourceManager.GetString("lblADTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance amount.
    '''</summary>
    Friend Shared ReadOnly Property lblADVAMT() As String
        Get
            Return ResourceManager.GetString("lblADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max advance amount.
    '''</summary>
    Friend Shared ReadOnly Property lblAVLADVAMT() As String
        Get
            Return ResourceManager.GetString("lblAVLADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Balance available.
    '''</summary>
    Friend Shared ReadOnly Property lblBALDEFOVD() As String
        Get
            Return ResourceManager.GetString("lblBALDEFOVD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bank account.
    '''</summary>
    Friend Shared ReadOnly Property lblBANKACCT() As String
        Get
            Return ResourceManager.GetString("lblBANKACCT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bank code.
    '''</summary>
    Friend Shared ReadOnly Property lblBANKCODE() As String
        Get
            Return ResourceManager.GetString("lblBANKCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min advance fee for bank.
    '''</summary>
    Friend Shared ReadOnly Property lblBNKMINBAL() As String
        Get
            Return ResourceManager.GetString("lblBNKMINBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance fee for bank.
    '''</summary>
    Friend Shared ReadOnly Property lblBNKRATE() As String
        Get
            Return ResourceManager.GetString("lblBNKRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max advance fee.
    '''</summary>
    Friend Shared ReadOnly Property lblCMPMAXBAL() As String
        Get
            Return ResourceManager.GetString("lblCMPMAXBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min advance fee.
    '''</summary>
    Friend Shared ReadOnly Property lblCMPMINBAL() As String
        Get
            Return ResourceManager.GetString("lblCMPMINBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("lblCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Full name.
    '''</summary>
    Friend Shared ReadOnly Property lblFULLNAME() As String
        Get
            Return ResourceManager.GetString("lblFULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID code.
    '''</summary>
    Friend Shared ReadOnly Property lblIDCODE() As String
        Get
            Return ResourceManager.GetString("lblIDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID date.
    '''</summary>
    Friend Shared ReadOnly Property lblIDDATE() As String
        Get
            Return ResourceManager.GetString("lblIDDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID place.
    '''</summary>
    Friend Shared ReadOnly Property lblIDPLACE() As String
        Get
            Return ResourceManager.GetString("lblIDPLACE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance fee.
    '''</summary>
    Friend Shared ReadOnly Property lblINTRATE() As String
        Get
            Return ResourceManager.GetString("lblINTRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Min advance.
    '''</summary>
    Friend Shared ReadOnly Property lblMINADVAMT() As String
        Get
            Return ResourceManager.GetString("lblMINADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max receiving amount.
    '''</summary>
    Friend Shared ReadOnly Property lblRCVADVAMT() As String
        Get
            Return ResourceManager.GetString("lblRCVADVAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer’s advance remain limit of the day.
    '''</summary>
    Friend Shared ReadOnly Property lblREMAINADV() As String
        Get
            Return ResourceManager.GetString("lblREMAINADV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Company’s advance remain limit of the day.
    '''</summary>
    Friend Shared ReadOnly Property lblREMAINADV_SYS() As String
        Get
            Return ResourceManager.GetString("lblREMAINADV_SYS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT.
    '''</summary>
    Friend Shared ReadOnly Property lblVAT() As String
        Get
            Return ResourceManager.GetString("lblVAT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Input must be grester than 0!.
    '''</summary>
    Friend Shared ReadOnly Property msgtxtADVAMTERROR() As String
        Get
            Return ResourceManager.GetString("msgtxtADVAMTERROR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Advance amount must be greater than min amount. Please correct !.
    '''</summary>
    Friend Shared ReadOnly Property msgtxtADVAMTNOTVALID() As String
        Get
            Return ResourceManager.GetString("msgtxtADVAMTNOTVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Create report sucessfully.
    '''</summary>
    Friend Shared ReadOnly Property ReportCreateSucessfully() As String
        Get
            Return ResourceManager.GetString("ReportCreateSucessfully", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trasaction successful.
    '''</summary>
    Friend Shared ReadOnly Property TransactionSuccessful() As String
        Get
            Return ResourceManager.GetString("TransactionSuccessful", resourceCulture)
        End Get
    End Property
End Class
