'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class FrmMarketInfo_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.FrmMarketInfo-VN", GetType(FrmMarketInfo_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kết xuất dữ liệu thành công!.
    '''</summary>
    Friend Shared ReadOnly Property ExportSuccessful() As String
        Get
            Return ResourceManager.GetString("ExportSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tra cứu tin tức nhận định thị trường.
    '''</summary>
    Friend Shared ReadOnly Property FORM_TITLE() As String
        Get
            Return ResourceManager.GetString("FORM_TITLE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Click đúp vào từng dòng để xem nội dung chi tiết tin tức.
    '''</summary>
    Friend Shared ReadOnly Property LBLINFODETAIL() As String
        Get
            Return ResourceManager.GetString("LBLINFODETAIL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số hiệu bản tin.
    '''</summary>
    Friend Shared ReadOnly Property NEWS_ID() As String
        Get
            Return ResourceManager.GetString("NEWS_ID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không có dữ liệu để kết xuất!.
    '''</summary>
    Friend Shared ReadOnly Property NothingToExport() As String
        Get
            Return ResourceManager.GetString("NothingToExport", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày đăng.
    '''</summary>
    Friend Shared ReadOnly Property POST_DATE() As String
        Get
            Return ResourceManager.GetString("POST_DATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số thứ tự.
    '''</summary>
    Friend Shared ReadOnly Property STT() As String
        Get
            Return ResourceManager.GetString("STT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nội dung.
    '''</summary>
    Friend Shared ReadOnly Property TITLE() As String
        Get
            Return ResourceManager.GetString("TITLE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không hỗ trợ export ra file excel!.
    '''</summary>
    Friend Shared ReadOnly Property XLSFILENOTSUPPORT() As String
        Get
            Return ResourceManager.GetString("XLSFILENOTSUPPORT", resourceCulture)
        End Get
    End Property
End Class
