'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmODTransact_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmODTransact-EN", GetType(frmODTransact_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCANCEL() As String
        Get
            Return ResourceManager.GetString("btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &gt;.
    '''</summary>
    Friend Shared ReadOnly Property btnNext() As String
        Get
            Return ResourceManager.GetString("btnNext", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;.
    '''</summary>
    Friend Shared ReadOnly Property btnPrev() As String
        Get
            Return ResourceManager.GetString("btnPrev", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ceiling price is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CEILINGINVALID() As String
        Get
            Return ResourceManager.GetString("CEILINGINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ceiling price:.
    '''</summary>
    Friend Shared ReadOnly Property CEILINGPRICE() As String
        Get
            Return ResourceManager.GetString("CEILINGPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to All?.
    '''</summary>
    Friend Shared ReadOnly Property chkAllorNone() As String
        Get
            Return ResourceManager.GetString("chkAllorNone", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settlement cycle is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CLEARINGDAYINVALID() As String
        Get
            Return ResourceManager.GetString("CLEARINGDAYINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contract is invalid.
    '''</summary>
    Friend Shared ReadOnly Property CONTRACTINVALID() As String
        Get
            Return ResourceManager.GetString("CONTRACTINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code:.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expired date is invalid.
    '''</summary>
    Friend Shared ReadOnly Property ERR_EXPIREDDATE_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_EXPIREDDATE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This field can not be null!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_FIELD_NULL() As String
        Get
            Return ResourceManager.GetString("ERR_FIELD_NULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Product type not found.
    '''</summary>
    Friend Shared ReadOnly Property ERR_PRODUCTTYPE_NOTFOUND() As String
        Get
            Return ResourceManager.GetString("ERR_PRODUCTTYPE_NOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid securities information!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_SEC_INFO() As String
        Get
            Return ResourceManager.GetString("ERR_SEC_INFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floor price is invalid.
    '''</summary>
    Friend Shared ReadOnly Property FLOORINVALID() As String
        Get
            Return ResourceManager.GetString("FLOORINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Floor price:.
    '''</summary>
    Friend Shared ReadOnly Property FLOORPRICE() As String
        Get
            Return ResourceManager.GetString("FLOORPRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Authorize information management.
    '''</summary>
    Friend Shared ReadOnly Property frm_CFAUTH() As String
        Get
            Return ResourceManager.GetString("frm_CFAUTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer information management.
    '''</summary>
    Friend Shared ReadOnly Property frm_CFMAST() As String
        Get
            Return ResourceManager.GetString("frm_CFMAST", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fullname:.
    '''</summary>
    Friend Shared ReadOnly Property FULLNAME() As String
        Get
            Return ResourceManager.GetString("FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Identification:.
    '''</summary>
    Friend Shared ReadOnly Property IDCODE() As String
        Get
            Return ResourceManager.GetString("IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contract no:.
    '''</summary>
    Friend Shared ReadOnly Property lblAFACCTNO() As String
        Get
            Return ResourceManager.GetString("lblAFACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Calendar:.
    '''</summary>
    Friend Shared ReadOnly Property lblCalendar() As String
        Get
            Return ResourceManager.GetString("lblCalendar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI balance:.
    '''</summary>
    Friend Shared ReadOnly Property lblCIBalance() As String
        Get
            Return ResourceManager.GetString("lblCIBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settlement cycle:.
    '''</summary>
    Friend Shared ReadOnly Property lblClearingDay() As String
        Get
            Return ResourceManager.GetString("lblClearingDay", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Consultant:.
    '''</summary>
    Friend Shared ReadOnly Property lblConsultant() As String
        Get
            Return ResourceManager.GetString("lblConsultant", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description:.
    '''</summary>
    Friend Shared ReadOnly Property lblDescription() As String
        Get
            Return ResourceManager.GetString("lblDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exec type:.
    '''</summary>
    Friend Shared ReadOnly Property lblExecType() As String
        Get
            Return ResourceManager.GetString("lblExecType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expired date:.
    '''</summary>
    Friend Shared ReadOnly Property lblExpiredDate() As String
        Get
            Return ResourceManager.GetString("lblExpiredDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Full name:.
    '''</summary>
    Friend Shared ReadOnly Property lblFullName() As String
        Get
            Return ResourceManager.GetString("lblFullName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to License.
    '''</summary>
    Friend Shared ReadOnly Property lblLicense() As String
        Get
            Return ResourceManager.GetString("lblLicense", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Limit price:.
    '''</summary>
    Friend Shared ReadOnly Property lblLimitPrice() As String
        Get
            Return ResourceManager.GetString("lblLimitPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Match type:.
    '''</summary>
    Friend Shared ReadOnly Property lblMatchType() As String
        Get
            Return ResourceManager.GetString("lblMatchType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order type:.
    '''</summary>
    Friend Shared ReadOnly Property lblOrderType() As String
        Get
            Return ResourceManager.GetString("lblOrderType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price type:.
    '''</summary>
    Friend Shared ReadOnly Property lblPriceType() As String
        Get
            Return ResourceManager.GetString("lblPriceType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity:.
    '''</summary>
    Friend Shared ReadOnly Property lblQuantity() As String
        Get
            Return ResourceManager.GetString("lblQuantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reference:.
    '''</summary>
    Friend Shared ReadOnly Property lblReference() As String
        Get
            Return ResourceManager.GetString("lblReference", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE balance:.
    '''</summary>
    Friend Shared ReadOnly Property lblSEBalance() As String
        Get
            Return ResourceManager.GetString("lblSEBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Stop price:.
    '''</summary>
    Friend Shared ReadOnly Property lblStopPrice() As String
        Get
            Return ResourceManager.GetString("lblStopPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Symbol:.
    '''</summary>
    Friend Shared ReadOnly Property lblSymbol() As String
        Get
            Return ResourceManager.GetString("lblSymbol", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Term.
    '''</summary>
    Friend Shared ReadOnly Property lblTerm() As String
        Get
            Return ResourceManager.GetString("lblTerm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Time type:.
    '''</summary>
    Friend Shared ReadOnly Property lblTimeType() As String
        Get
            Return ResourceManager.GetString("lblTimeType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Voucher:.
    '''</summary>
    Friend Shared ReadOnly Property lblVoucher() As String
        Get
            Return ResourceManager.GetString("lblVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CustID.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_CUSTID() As String
        Get
            Return ResourceManager.GetString("MEMBER_CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fullname.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_FULLNAME() As String
        Get
            Return ResourceManager.GetString("MEMBER_FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Idcode.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDCODE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ref.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REF() As String
        Get
            Return ResourceManager.GetString("MEMBER_REF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYP() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price should be numeric value.
    '''</summary>
    Friend Shared ReadOnly Property PRICEISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("PRICEISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity should be numeric value.
    '''</summary>
    Friend Shared ReadOnly Property QTTYISNOTNUMBER() As String
        Get
            Return ResourceManager.GetString("QTTYISNOTNUMBER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lot:.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOT() As String
        Get
            Return ResourceManager.GetString("TRADELOT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tradelot is invalid.
    '''</summary>
    Friend Shared ReadOnly Property TRADELOTINVALID() As String
        Get
            Return ResourceManager.GetString("TRADELOTINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unit:.
    '''</summary>
    Friend Shared ReadOnly Property TRADEUNIT() As String
        Get
            Return ResourceManager.GetString("TRADEUNIT", resourceCulture)
        End Get
    End Property
End Class
