'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
Friend Class frmODMASTCOMPARE_EN

    Private Shared resourceMan As Global.System.Resources.ResourceManager

    Private Shared resourceCulture As Global.System.Globalization.CultureInfo

    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
    Friend Sub New()
        MyBase.New()
    End Sub

    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmODMASTCOMPARE-EN", GetType(frmCAVOTING_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property

    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = value
        End Set
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property _exit() As String
        Get
            Return ResourceManager.GetString("exit", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Add.
    '''</summary>
    Friend Shared ReadOnly Property ADD() As String
        Get
            Return ResourceManager.GetString("ADD", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Add new successful.
    '''</summary>
    Friend Shared ReadOnly Property AddnewSuccessful() As String
        Get
            Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Address.
    '''</summary>
    Friend Shared ReadOnly Property ADDRESS() As String
        Get
            Return ResourceManager.GetString("ADDRESS", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Amount must be greater than 0.
    '''</summary>
    Friend Shared ReadOnly Property AMOUNTERR() As String
        Get
            Return ResourceManager.GetString("AMOUNTERR", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Approve.
    '''</summary>
    Friend Shared ReadOnly Property Approve() As String
        Get
            Return ResourceManager.GetString("Approve", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Approve successful.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to CA Code.
    '''</summary>
    Friend Shared ReadOnly Property CAID() As String
        Get
            Return ResourceManager.GetString("CAID", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized resource of type System.Data.DataTable similar to COMBOBOX.
    '''</summary>
    Friend Shared ReadOnly Property cboLink_ComboData() As System.Data.DataTable
        Get
            Dim obj As Object = ResourceManager.GetObject("cboLink.ComboData", resourceCulture)
            Return CType(obj, System.Data.DataTable)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Must choose securities ID.
    '''</summary>
    Friend Shared ReadOnly Property CKCCEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CKCCEmptyMsg", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Confirm.
    '''</summary>
    Friend Shared ReadOnly Property confirm() As String
        Get
            Return ResourceManager.GetString("confirm", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Broker firm.
    '''</summary>
    Friend Shared ReadOnly Property CTCK() As String
        Get
            Return ResourceManager.GetString("CTCK", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Invalid securities company !.
    '''</summary>
    Friend Shared ReadOnly Property CTCKEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CTCKEmptyMsg", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Trading account.
    '''</summary>
    Friend Shared ReadOnly Property Custodycd() As String
        Get
            Return ResourceManager.GetString("Custodycd", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Invalid Trading account !.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD_INVALID_LENGTH() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD_INVALID_LENGTH", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Invalid trading account number.
    '''</summary>
    Friend Shared ReadOnly Property CustodycdEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CustodycdEmptyMsg", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Delete.
    '''</summary>
    Friend Shared ReadOnly Property DEL() As String
        Get
            Return ResourceManager.GetString("DEL", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property desc() As String
        Get
            Return ResourceManager.GetString("desc", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to CKCC code must not be duplicated!.
    '''</summary>
    Friend Shared ReadOnly Property DUPLICATECKCC() As String
        Get
            Return ResourceManager.GetString("DUPLICATECKCC", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Fund code.
    '''</summary>
    Friend Shared ReadOnly Property ETFID() As String
        Get
            Return ResourceManager.GetString("ETFID", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Fund name.
    '''</summary>
    Friend Shared ReadOnly Property ETFNAME() As String
        Get
            Return ResourceManager.GetString("ETFNAME", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Invalid fund code.
    '''</summary>
    Friend Shared ReadOnly Property ETFNewEmptyMsg() As String
        Get
            Return ResourceManager.GetString("ETFNewEmptyMsg", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Creation units.
    '''</summary>
    Friend Shared ReadOnly Property ETXQUANTITY() As String
        Get
            Return ResourceManager.GetString("ETXQUANTITY", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Fee.
    '''</summary>
    Friend Shared ReadOnly Property FEE() As String
        Get
            Return ResourceManager.GetString("FEE", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Fee must be greater than or equal 0.
    '''</summary>
    Friend Shared ReadOnly Property FEEERR() As String
        Get
            Return ResourceManager.GetString("FEEERR", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Enter ETF swap result.
    '''</summary>
    Friend Shared ReadOnly Property frmSBETF() As String
        Get
            Return ResourceManager.GetString("frmSBETF", resourceCulture)
        End Get
    End Property

    '''<summary>
    '''  Looks up a localized string similar to Full name.
    '''</summary>
    Friend Shared ReadOnly Property Fullname() As String
        Get
            Return ResourceManager.GetString("Fullname", resourceCulture)
        End Get
    End Property
End Class
