'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmOperation_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmOperation-EN", GetType(frmOperation_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AUTOGV: Auto run general view.
    '''</summary>
    Friend Shared ReadOnly Property AUTOGV() As String
        Get
            Return ResourceManager.GetString("AUTOGV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to BAMTTRF: Tạo bảng kê tiền mua CK.
    '''</summary>
    Friend Shared ReadOnly Property BAMTTRF() As String
        Get
            Return ResourceManager.GetString("BAMTTRF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to BFEETRF: Tạo bảng kê phí mua CK.
    '''</summary>
    Friend Shared ReadOnly Property BFEETRF() As String
        Get
            Return ResourceManager.GetString("BFEETRF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reset &amp;cache.
    '''</summary>
    Friend Shared ReadOnly Property btnCache() As String
        Get
            Return ResourceManager.GetString("btnCache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property btnClose() As String
        Get
            Return ResourceManager.GetString("btnClose", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Submit.
    '''</summary>
    Friend Shared ReadOnly Property btnSubmit() As String
        Get
            Return ResourceManager.GetString("btnSubmit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reset &amp;ticker.
    '''</summary>
    Friend Shared ReadOnly Property btnTicker() As String
        Get
            Return ResourceManager.GetString("btnTicker", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Auto-process (s).
    '''</summary>
    Friend Shared ReadOnly Property CheckBox1() As String
        Get
            Return ResourceManager.GetString("CheckBox1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Control board.
    '''</summary>
    Friend Shared ReadOnly Property frmOperation() As String
        Get
            Return ResourceManager.GetString("frmOperation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GET_ORDERBOOK: Get HoSE Order book.
    '''</summary>
    Friend Shared ReadOnly Property GET_ORDERBOOK() As String
        Get
            Return ResourceManager.GetString("GET_ORDERBOOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GET_TRADEBOOK: Get HoSE Trade book.
    '''</summary>
    Friend Shared ReadOnly Property GET_TRADEBOOK() As String
        Get
            Return ResourceManager.GetString("GET_TRADEBOOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GET_VNMARKETWATCH: Get HaSTC Market watch.
    '''</summary>
    Friend Shared ReadOnly Property GET_VNMARKETWATCH() As String
        Get
            Return ResourceManager.GetString("GET_VNMARKETWATCH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to GET_VSMARKETWATCH: Get HoSE Market watch.
    '''</summary>
    Friend Shared ReadOnly Property GET_VSMARKETWATCH() As String
        Get
            Return ResourceManager.GetString("GET_VSMARKETWATCH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEX8879: Tạo bảng kê tiền bán CK lô lẻ.
    '''</summary>
    Friend Shared ReadOnly Property RMEX8879() As String
        Get
            Return ResourceManager.GetString("RMEX8879", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEX8879DF: Tạo bảng kê thuế bán CK lô lẻ.
    '''</summary>
    Friend Shared ReadOnly Property RMEX8879DF() As String
        Get
            Return ResourceManager.GetString("RMEX8879DF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXCA3350: Tạo bảng kê tiền cổ tức.
    '''</summary>
    Friend Shared ReadOnly Property RMEXCA3350() As String
        Get
            Return ResourceManager.GetString("RMEXCA3350", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXCA3350DF: Tạo bảng kê thuế cổ tức.
    '''</summary>
    Friend Shared ReadOnly Property RMEXCA3350DF() As String
        Get
            Return ResourceManager.GetString("RMEXCA3350DF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXCA3384: Tạo bảng kê đăng ký quyền mua.
    '''</summary>
    Friend Shared ReadOnly Property RMEXCA3384() As String
        Get
            Return ResourceManager.GetString("RMEXCA3384", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXCA3386: Tạo bảng kê hủy đăng ký quyền mua.
    '''</summary>
    Friend Shared ReadOnly Property RMEXCA3386() As String
        Get
            Return ResourceManager.GetString("RMEXCA3386", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXHLDQUEUE: Execute Hold/Unhold queue.
    '''</summary>
    Friend Shared ReadOnly Property RMEXHLDQUEUE() As String
        Get
            Return ResourceManager.GetString("RMEXHLDQUEUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXTRFQUEUE: Execute Batch transfer.
    '''</summary>
    Friend Shared ReadOnly Property RMEXTRFQUEUE() As String
        Get
            Return ResourceManager.GetString("RMEXTRFQUEUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RMEXTRFSTS: Get EOD Report status.
    '''</summary>
    Friend Shared ReadOnly Property RMEXTRFSTS() As String
        Get
            Return ResourceManager.GetString("RMEXTRFSTS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDCMP: Send order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDCMP() As String
        Get
            Return ResourceManager.GetString("SENDCMP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDGTC: Send GTC order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDGTC() As String
        Get
            Return ResourceManager.GetString("SENDGTC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDHAGTC: Send Hastc GTC order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDHAGTC() As String
        Get
            Return ResourceManager.GetString("SENDHAGTC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDHASL: Send Hastc stop limit order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDHASL() As String
        Get
            Return ResourceManager.GetString("SENDHASL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDHOGTC: Send Hose GTC order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDHOGTC() As String
        Get
            Return ResourceManager.GetString("SENDHOGTC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SENDHOSL: Send Hostc stop limit order from FO to company.
    '''</summary>
    Friend Shared ReadOnly Property SENDHOSL() As String
        Get
            Return ResourceManager.GetString("SENDHOSL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SMS:Send sms to customer.
    '''</summary>
    Friend Shared ReadOnly Property SENDSMS() As String
        Get
            Return ResourceManager.GetString("SENDSMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_MAP_SECURITIESINFO: Synchronize Securities with Stock Exchange.
    '''</summary>
    Friend Shared ReadOnly Property START_MAP_SECURITIESINFO() As String
        Get
            Return ResourceManager.GetString("START_MAP_SECURITIESINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_MAP_STCORDERBOOK: Map exchange order book to company order book.
    '''</summary>
    Friend Shared ReadOnly Property START_MAP_STCORDERBOOK() As String
        Get
            Return ResourceManager.GetString("START_MAP_STCORDERBOOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_MAP_STCTRADEBOOK: Map exchange trade book to company order book.
    '''</summary>
    Friend Shared ReadOnly Property START_MAP_STCTRADEBOOK() As String
        Get
            Return ResourceManager.GetString("START_MAP_STCTRADEBOOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_VNMKTINFO: Start HaSTC Listed market info download.
    '''</summary>
    Friend Shared ReadOnly Property START_VNMKTINFO() As String
        Get
            Return ResourceManager.GetString("START_VNMKTINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_VNTRADE: Start HaSTC Listed trading data download.
    '''</summary>
    Friend Shared ReadOnly Property START_VNTRADE() As String
        Get
            Return ResourceManager.GetString("START_VNTRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_VSMKTINFO: Start HoSE Listed market info download.
    '''</summary>
    Friend Shared ReadOnly Property START_VSMKTINFO() As String
        Get
            Return ResourceManager.GetString("START_VSMKTINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to START_VSTRADE: Start HoSE Listed trading data download.
    '''</summary>
    Friend Shared ReadOnly Property START_VSTRADE() As String
        Get
            Return ResourceManager.GetString("START_VSTRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SYNCTRANS: Process asynchronous transaction.
    '''</summary>
    Friend Shared ReadOnly Property SYNCTRANS() As String
        Get
            Return ResourceManager.GetString("SYNCTRANS", resourceCulture)
        End Get
    End Property
End Class
