'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmReChangeRe_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmReChangeRe-EN", GetType(frmReChangeRe_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sub account.
    '''</summary>
    Friend Shared ReadOnly Property ACCTNO() As String
        Get
            Return ResourceManager.GetString("ACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apply.
    '''</summary>
    Friend Shared ReadOnly Property btnChange() As String
        Get
            Return ResourceManager.GetString("btnChange", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ok.
    '''</summary>
    Friend Shared ReadOnly Property btnOk() As String
        Get
            Return ResourceManager.GetString("btnOk", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search.
    '''</summary>
    Friend Shared ReadOnly Property btnSearch() As String
        Get
            Return ResourceManager.GetString("btnSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Care by.
    '''</summary>
    Friend Shared ReadOnly Property CAREBY() As String
        Get
            Return ResourceManager.GetString("CAREBY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change care by.
    '''</summary>
    Friend Shared ReadOnly Property CONFIRM() As String
        Get
            Return ResourceManager.GetString("CONFIRM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer ID.
    '''</summary>
    Friend Shared ReadOnly Property CUSTID() As String
        Get
            Return ResourceManager.GetString("CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody code.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Done.
    '''</summary>
    Friend Shared ReadOnly Property DONE() As String
        Get
            Return ResourceManager.GetString("DONE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date.
    '''</summary>
    Friend Shared ReadOnly Property FRDATE() As String
        Get
            Return ResourceManager.GetString("FRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change care by.
    '''</summary>
    Friend Shared ReadOnly Property frmReChangeRe() As String
        Get
            Return ResourceManager.GetString("frmReChangeRe", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Full name.
    '''</summary>
    Friend Shared ReadOnly Property FULLNAME() As String
        Get
            Return ResourceManager.GetString("FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search information.
    '''</summary>
    Friend Shared ReadOnly Property grpSearch() As String
        Get
            Return ResourceManager.GetString("grpSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The Careby is not found.
    '''</summary>
    Friend Shared ReadOnly Property INVALCAREBY() As String
        Get
            Return ResourceManager.GetString("INVALCAREBY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date must less than to date.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDDATE() As String
        Get
            Return ResourceManager.GetString("INVALIDDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date must be greater or equal current date.
    '''</summary>
    Friend Shared ReadOnly Property INVALIDFRDATE() As String
        Get
            Return ResourceManager.GetString("INVALIDFRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The broker account is not found!.
    '''</summary>
    Friend Shared ReadOnly Property INVALREACCOUNT() As String
        Get
            Return ResourceManager.GetString("INVALREACCOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change care by.
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Care by.
    '''</summary>
    Friend Shared ReadOnly Property lblCareby() As String
        Get
            Return ResourceManager.GetString("lblCareby", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Care by new.
    '''</summary>
    Friend Shared ReadOnly Property lblCarebyNew() As String
        Get
            Return ResourceManager.GetString("lblCarebyNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Future care by new.
    '''</summary>
    Friend Shared ReadOnly Property lblFCarebyNew() As String
        Get
            Return ResourceManager.GetString("lblFCarebyNew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to From date.
    '''</summary>
    Friend Shared ReadOnly Property lblFromDate() As String
        Get
            Return ResourceManager.GetString("lblFromDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction date.
    '''</summary>
    Friend Shared ReadOnly Property lblFURDATE() As String
        Get
            Return ResourceManager.GetString("lblFURDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Days.
    '''</summary>
    Friend Shared ReadOnly Property lblFURDAYS() As String
        Get
            Return ResourceManager.GetString("lblFURDAYS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expire date.
    '''</summary>
    Friend Shared ReadOnly Property lblFurToDate() As String
        Get
            Return ResourceManager.GetString("lblFurToDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Future RE old account.
    '''</summary>
    Friend Shared ReadOnly Property lblFUTREACCTNO() As String
        Get
            Return ResourceManager.GetString("lblFUTREACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Future RE new account.
    '''</summary>
    Friend Shared ReadOnly Property lblFUTREACCTNONEW() As String
        Get
            Return ResourceManager.GetString("lblFUTREACCTNONEW", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Old RE account.
    '''</summary>
    Friend Shared ReadOnly Property lblReAcctno() As String
        Get
            Return ResourceManager.GetString("lblReAcctno", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New RE account.
    '''</summary>
    Friend Shared ReadOnly Property lblReDG() As String
        Get
            Return ResourceManager.GetString("lblReDG", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to To date.
    '''</summary>
    Friend Shared ReadOnly Property lblToDate() As String
        Get
            Return ResourceManager.GetString("lblToDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RE code is not null.
    '''</summary>
    Friend Shared ReadOnly Property REISNOTNULL() As String
        Get
            Return ResourceManager.GetString("REISNOTNULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to To date.
    '''</summary>
    Friend Shared ReadOnly Property TODATE() As String
        Get
            Return ResourceManager.GetString("TODATE", resourceCulture)
        End Get
    End Property
End Class
