'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmReApprove_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmReApprove-VN", GetType(frmReApprove_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property ACCTNO() As String
        Get
            Return ResourceManager.GetString("ACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt giao dịch thành công.
    '''</summary>
    Friend Shared ReadOnly Property ApprovedSuccessful() As String
        Get
            Return ResourceManager.GetString("ApprovedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Hủy.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Duyệt.
    '''</summary>
    Friend Shared ReadOnly Property btnChange() As String
        Get
            Return ResourceManager.GetString("btnChange", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đ&amp;óng.
    '''</summary>
    Friend Shared ReadOnly Property btnClose() As String
        Get
            Return ResourceManager.GetString("btnClose", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Ghi.
    '''</summary>
    Friend Shared ReadOnly Property btnOk() As String
        Get
            Return ResourceManager.GetString("btnOk", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tìm kiếm.
    '''</summary>
    Friend Shared ReadOnly Property btnSearch() As String
        Get
            Return ResourceManager.GetString("btnSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên khách hàng.
    '''</summary>
    Friend Shared ReadOnly Property CFNAME() As String
        Get
            Return ResourceManager.GetString("CFNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Gán môi giới chăm sóc hộ cho các tiểu khoản .
    '''</summary>
    Friend Shared ReadOnly Property CONFIRM() As String
        Get
            Return ResourceManager.GetString("CONFIRM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số lưu ký.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Từ ngày.
    '''</summary>
    Friend Shared ReadOnly Property FRDATE() As String
        Get
            Return ResourceManager.GetString("FRDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt giao dịch gán môi giới.
    '''</summary>
    Friend Shared ReadOnly Property frmReApprove() As String
        Get
            Return ResourceManager.GetString("frmReApprove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duyệt giao dịch gán môi giới.
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã môi giới.
    '''</summary>
    Friend Shared ReadOnly Property lblReAcctno() As String
        Get
            Return ResourceManager.GetString("lblReAcctno", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Danh sách giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property rbRemiser() As String
        Get
            Return ResourceManager.GetString("rbRemiser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản môi giới.
    '''</summary>
    Friend Shared ReadOnly Property REACCTNO() As String
        Get
            Return ResourceManager.GetString("REACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên môi giới.
    '''</summary>
    Friend Shared ReadOnly Property REMISERNAME() As String
        Get
            Return ResourceManager.GetString("REMISERNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vai trò.
    '''</summary>
    Friend Shared ReadOnly Property REROLE() As String
        Get
            Return ResourceManager.GetString("REROLE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đến ngày.
    '''</summary>
    Friend Shared ReadOnly Property TODATE() As String
        Get
            Return ResourceManager.GetString("TODATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property TXDATE() As String
        Get
            Return ResourceManager.GetString("TXDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mô tả giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property TXDESC() As String
        Get
            Return ResourceManager.GetString("TXDESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số chứng từ.
    '''</summary>
    Friend Shared ReadOnly Property TXNUM() As String
        Get
            Return ResourceManager.GetString("TXNUM", resourceCulture)
        End Get
    End Property
End Class
