'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmSBETF_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmSBETF-EN", GetType(frmSBETF_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exit.
    '''</summary>
    Friend Shared ReadOnly Property _exit() As String
        Get
            Return ResourceManager.GetString("exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add.
    '''</summary>
    Friend Shared ReadOnly Property ADD() As String
        Get
            Return ResourceManager.GetString("ADD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add new successful.
    '''</summary>
    Friend Shared ReadOnly Property AddnewSuccessful() As String
        Get
            Return ResourceManager.GetString("AddnewSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Address.
    '''</summary>
    Friend Shared ReadOnly Property ADDRESS() As String
        Get
            Return ResourceManager.GetString("ADDRESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount must be greater than 0.
    '''</summary>
    Friend Shared ReadOnly Property AMOUNTERR() As String
        Get
            Return ResourceManager.GetString("AMOUNTERR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve.
    '''</summary>
    Friend Shared ReadOnly Property Approve() As String
        Get
            Return ResourceManager.GetString("Approve", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve successful.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Data.DataTable similar to COMBOBOX.
    '''</summary>
    Friend Shared ReadOnly Property cboLink_ComboData() As System.Data.DataTable
        Get
            Dim obj As Object = ResourceManager.GetObject("cboLink.ComboData", resourceCulture)
            Return CType(obj,System.Data.DataTable)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Must choose securities ID.
    '''</summary>
    Friend Shared ReadOnly Property CKCCEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CKCCEmptyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm.
    '''</summary>
    Friend Shared ReadOnly Property confirm() As String
        Get
            Return ResourceManager.GetString("confirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Broker firm.
    '''</summary>
    Friend Shared ReadOnly Property CTCK() As String
        Get
            Return ResourceManager.GetString("CTCK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid securities company !.
    '''</summary>
    Friend Shared ReadOnly Property CTCKEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CTCKEmptyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trading account.
    '''</summary>
    Friend Shared ReadOnly Property Custodycd() As String
        Get
            Return ResourceManager.GetString("Custodycd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Trading account !.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD_INVALID_LENGTH() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD_INVALID_LENGTH", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid trading account number.
    '''</summary>
    Friend Shared ReadOnly Property CustodycdEmptyMsg() As String
        Get
            Return ResourceManager.GetString("CustodycdEmptyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete.
    '''</summary>
    Friend Shared ReadOnly Property DEL() As String
        Get
            Return ResourceManager.GetString("DEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property desc() As String
        Get
            Return ResourceManager.GetString("desc", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ETF swap transaction result.
    '''</summary>
    Friend Shared ReadOnly Property DESCETF() As String
        Get
            Return ResourceManager.GetString("DESCETF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Different amount is not equal 0.
    '''</summary>
    Friend Shared ReadOnly Property DIFFE() As String
        Get
            Return ResourceManager.GetString("DIFFE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CKCC code must not be duplicated!.
    '''</summary>
    Friend Shared ReadOnly Property DUPLICATECKCC() As String
        Get
            Return ResourceManager.GetString("DUPLICATECKCC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fund code.
    '''</summary>
    Friend Shared ReadOnly Property ETFID() As String
        Get
            Return ResourceManager.GetString("ETFID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fund name.
    '''</summary>
    Friend Shared ReadOnly Property ETFNAME() As String
        Get
            Return ResourceManager.GetString("ETFNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid fund code.
    '''</summary>
    Friend Shared ReadOnly Property ETFNewEmptyMsg() As String
        Get
            Return ResourceManager.GetString("ETFNewEmptyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Creation units.
    '''</summary>
    Friend Shared ReadOnly Property ETXQUANTITY() As String
        Get
            Return ResourceManager.GetString("ETXQUANTITY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee.
    '''</summary>
    Friend Shared ReadOnly Property FEE() As String
        Get
            Return ResourceManager.GetString("FEE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fee must be greater than or equal 0.
    '''</summary>
    Friend Shared ReadOnly Property FEEERR() As String
        Get
            Return ResourceManager.GetString("FEEERR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter ETF swap result.
    '''</summary>
    Friend Shared ReadOnly Property frmSBETF() As String
        Get
            Return ResourceManager.GetString("frmSBETF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Full name.
    '''</summary>
    Friend Shared ReadOnly Property Fullname() As String
        Get
            Return ResourceManager.GetString("Fullname", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Creation basket information.
    '''</summary>
    Friend Shared ReadOnly Property genaraletf() As String
        Get
            Return ResourceManager.GetString("genaraletf", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Creation basket must be created.
    '''</summary>
    Friend Shared ReadOnly Property GridEmpty() As String
        Get
            Return ResourceManager.GetString("GridEmpty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount.
    '''</summary>
    Friend Shared ReadOnly Property mskamount() As String
        Get
            Return ResourceManager.GetString("mskamount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Difference.
    '''</summary>
    Friend Shared ReadOnly Property mskdiffe() As String
        Get
            Return ResourceManager.GetString("mskdiffe", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Record difference amount.
    '''</summary>
    Friend Shared ReadOnly Property mskdiffe_db() As String
        Get
            Return ResourceManager.GetString("mskdiffe_db", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to NAV price.
    '''</summary>
    Friend Shared ReadOnly Property msknavccq() As String
        Get
            Return ResourceManager.GetString("msknavccq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to NAV price must be greater than 0.
    '''</summary>
    Friend Shared ReadOnly Property MSKRRR() As String
        Get
            Return ResourceManager.GetString("MSKRRR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Payment date.
    '''</summary>
    Friend Shared ReadOnly Property msksetdate() As String
        Get
            Return ResourceManager.GetString("msksetdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trading date.
    '''</summary>
    Friend Shared ReadOnly Property msktxdate() As String
        Get
            Return ResourceManager.GetString("msktxdate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to General information.
    '''</summary>
    Friend Shared ReadOnly Property panelgenreral() As String
        Get
            Return ResourceManager.GetString("panelgenreral", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity.
    '''</summary>
    Friend Shared ReadOnly Property QTTY() As String
        Get
            Return ResourceManager.GetString("QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Creation units must be greater than 0.
    '''</summary>
    Friend Shared ReadOnly Property QTTYERR() As String
        Get
            Return ResourceManager.GetString("QTTYERR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Securities balance.
    '''</summary>
    Friend Shared ReadOnly Property QTTYNOTENOUGHT() As String
        Get
            Return ResourceManager.GetString("QTTYNOTENOUGHT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to not enough !.
    '''</summary>
    Friend Shared ReadOnly Property QTTYNOTENOUGHT_1() As String
        Get
            Return ResourceManager.GetString("QTTYNOTENOUGHT_1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to RefID.
    '''</summary>
    Friend Shared ReadOnly Property REFERENCEID() As String
        Get
            Return ResourceManager.GetString("REFERENCEID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reject.
    '''</summary>
    Friend Shared ReadOnly Property reject() As String
        Get
            Return ResourceManager.GetString("reject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tax.
    '''</summary>
    Friend Shared ReadOnly Property TAX() As String
        Get
            Return ResourceManager.GetString("TAX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tax must be greater than or equal 0.
    '''</summary>
    Friend Shared ReadOnly Property TAXERR() As String
        Get
            Return ResourceManager.GetString("TAXERR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Transaction is successful. .
    '''</summary>
    Friend Shared ReadOnly Property TRANSSUCCESS() As String
        Get
            Return ResourceManager.GetString("TRANSSUCCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This transaction must be appproved!.
    '''</summary>
    Friend Shared ReadOnly Property TRANSSUCCESS1() As String
        Get
            Return ResourceManager.GetString("TRANSSUCCESS1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Authorized Participant.
    '''</summary>
    Friend Shared ReadOnly Property TVLQNAME() As String
        Get
            Return ResourceManager.GetString("TVLQNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trans type.
    '''</summary>
    Friend Shared ReadOnly Property type() As String
        Get
            Return ResourceManager.GetString("type", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trans type is mandatory.
    '''</summary>
    Friend Shared ReadOnly Property TypeEmptyMsg() As String
        Get
            Return ResourceManager.GetString("TypeEmptyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount cannot be negative!.
    '''</summary>
    Friend Shared ReadOnly Property valueQTTY() As String
        Get
            Return ResourceManager.GetString("valueQTTY", resourceCulture)
        End Get
    End Property
End Class
