'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmTeleInq_VN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmTeleInq-VN", GetType(frmTeleInq_VN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiểu khoản giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property ACCNAME() As String
        Get
            Return ResourceManager.GetString("ACCNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiểu khoản đặt lệnh.
    '''</summary>
    Friend Shared ReadOnly Property ACCTNO() As String
        Get
            Return ResourceManager.GetString("ACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền bán chờ về.
    '''</summary>
    Friend Shared ReadOnly Property AVLADVANCE() As String
        Get
            Return ResourceManager.GetString("AVLADVANCE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số dư tiền trên tiểu khoản.
    '''</summary>
    Friend Shared ReadOnly Property BALANCE() As String
        Get
            Return ResourceManager.GetString("BALANCE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 2.Ứng trước.
    '''</summary>
    Friend Shared ReadOnly Property btnAdvance() As String
        Get
            Return ResourceManager.GetString("btnAdvance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Đóng.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 8.Đổi PIN.
    '''</summary>
    Friend Shared ReadOnly Property btnChangePIN() As String
        Get
            Return ResourceManager.GetString("btnChangePIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI Block.
    '''</summary>
    Friend Shared ReadOnly Property btnCIBlocked() As String
        Get
            Return ResourceManager.GetString("btnCIBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI Decrease.
    '''</summary>
    Friend Shared ReadOnly Property btnCIDecrease() As String
        Get
            Return ResourceManager.GetString("btnCIDecrease", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI Increase.
    '''</summary>
    Friend Shared ReadOnly Property btnCIIncrease() As String
        Get
            Return ResourceManager.GetString("btnCIIncrease", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 3.Chuyển tiền.
    '''</summary>
    Friend Shared ReadOnly Property btnCITransfer() As String
        Get
            Return ResourceManager.GetString("btnCITransfer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CI Unblock.
    '''</summary>
    Friend Shared ReadOnly Property btnCIUnBlocked() As String
        Get
            Return ResourceManager.GetString("btnCIUnBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 6.TT 1Firm.
    '''</summary>
    Friend Shared ReadOnly Property btnOneFirm() As String
        Get
            Return ResourceManager.GetString("btnOneFirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kiểm tra.
    '''</summary>
    Friend Shared ReadOnly Property btnPinValidate() As String
        Get
            Return ResourceManager.GetString("btnPinValidate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 1.Đặt lệnh.
    '''</summary>
    Friend Shared ReadOnly Property btnPlaceOrder() As String
        Get
            Return ResourceManager.GetString("btnPlaceOrder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 4.ĐKQM.
    '''</summary>
    Friend Shared ReadOnly Property btnRightOff() As String
        Get
            Return ResourceManager.GetString("btnRightOff", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Tìm kiếm.
    '''</summary>
    Friend Shared ReadOnly Property btnSearch() As String
        Get
            Return ResourceManager.GetString("btnSearch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE Block.
    '''</summary>
    Friend Shared ReadOnly Property btnSEBlocked() As String
        Get
            Return ResourceManager.GetString("btnSEBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE Decrease.
    '''</summary>
    Friend Shared ReadOnly Property btnSEDecrease() As String
        Get
            Return ResourceManager.GetString("btnSEDecrease", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE Increase.
    '''</summary>
    Friend Shared ReadOnly Property btnSEIncrease() As String
        Get
            Return ResourceManager.GetString("btnSEIncrease", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 5.Chuyển CK.
    '''</summary>
    Friend Shared ReadOnly Property btnSETransfer() As String
        Get
            Return ResourceManager.GetString("btnSETransfer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SE Unblock.
    '''</summary>
    Friend Shared ReadOnly Property btnSEUnBlocked() As String
        Get
            Return ResourceManager.GetString("btnSEUnBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Chuyển.
    '''</summary>
    Friend Shared ReadOnly Property btnTranfer() As String
        Get
            Return ResourceManager.GetString("btnTranfer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 7.TT 2Firm.
    '''</summary>
    Friend Shared ReadOnly Property btnTwofirm() As String
        Get
            Return ResourceManager.GetString("btnTwofirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền cổ tức chờ về.
    '''</summary>
    Friend Shared ReadOnly Property CARECEIVING() As String
        Get
            Return ResourceManager.GetString("CARECEIVING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã KH người đặt lệnh.
    '''</summary>
    Friend Shared ReadOnly Property CUSTID() As String
        Get
            Return ResourceManager.GetString("CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tài khoản.
    '''</summary>
    Friend Shared ReadOnly Property CUSTODYCD() As String
        Get
            Return ResourceManager.GetString("CUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hãy chọn lệnh bạn muốn đẩy lên sàn!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_CHECK_ORDER() As String
        Get
            Return ResourceManager.GetString("ERR_CHECK_ORDER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã pin không chính xác!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_Incorrect() As String
        Get
            Return ResourceManager.GetString("ERR_Incorrect", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Vui lòng nhập mã pin!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_INSERTPIN() As String
        Get
            Return ResourceManager.GetString("ERR_INSERTPIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không thể kiểm tra mã pin!.
    '''</summary>
    Friend Shared ReadOnly Property ERR_Invalid() As String
        Get
            Return ResourceManager.GetString("ERR_Invalid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tra cứu khách hàng đặt lệnh qua điện thoại.
    '''</summary>
    Friend Shared ReadOnly Property frmTeleInq() As String
        Get
            Return ResourceManager.GetString("frmTeleInq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Người đặt lệnh.
    '''</summary>
    Friend Shared ReadOnly Property FULLNAME() As String
        Get
            Return ResourceManager.GetString("FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiểu khoản:.
    '''</summary>
    Friend Shared ReadOnly Property grbACCTNOINFO() As String
        Get
            Return ResourceManager.GetString("grbACCTNOINFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Có cuộc gọi mới, bạn có muốn chuyển xử lý cho cuộc gọi mới?.
    '''</summary>
    Friend Shared ReadOnly Property HAVENEWCALL() As String
        Get
            Return ResourceManager.GetString("HAVENEWCALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID.
    '''</summary>
    Friend Shared ReadOnly Property ID() As String
        Get
            Return ResourceManager.GetString("ID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số CMT người đặt lệnh.
    '''</summary>
    Friend Shared ReadOnly Property IDCODE() As String
        Get
            Return ResourceManager.GetString("IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ngày cấp.
    '''</summary>
    Friend Shared ReadOnly Property IDDATE() As String
        Get
            Return ResourceManager.GetString("IDDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nơi cấp.
    '''</summary>
    Friend Shared ReadOnly Property IDPLACE() As String
        Get
            Return ResourceManager.GetString("IDPLACE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Không tìm thấy thông tin khách hàng tương ứng với số điện thoại!.
    '''</summary>
    Friend Shared ReadOnly Property INFONOTFOUND() As String
        Get
            Return ResourceManager.GetString("INFONOTFOUND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Danh sách tiểu khoản giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property lblACCLIST() As String
        Get
            Return ResourceManager.GetString("lblACCLIST", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tài khoản :.
    '''</summary>
    Friend Shared ReadOnly Property lblACCTNO() As String
        Get
            Return ResourceManager.GetString("lblACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền khả dụng tại NH:.
    '''</summary>
    Friend Shared ReadOnly Property lblBankAVLBAL() As String
        Get
            Return ResourceManager.GetString("lblBankAVLBAL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền tại NH:.
    '''</summary>
    Friend Shared ReadOnly Property lblBankBalance() As String
        Get
            Return ResourceManager.GetString("lblBankBalance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Truy vấn tài khoản qua điện thoại.
    '''</summary>
    Friend Shared ReadOnly Property lblCaption() As String
        Get
            Return ResourceManager.GetString("lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tiền mặt - Sức mua.
    '''</summary>
    Friend Shared ReadOnly Property lblCI() As String
        Get
            Return ResourceManager.GetString("lblCI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CMT:IDCODE - IDDATE - IDPLACE .
    '''</summary>
    Friend Shared ReadOnly Property lblCODE() As String
        Get
            Return ResourceManager.GetString("lblCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số TK lưu ký.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTID() As String
        Get
            Return ResourceManager.GetString("lblCUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TK lưu ký.
    '''</summary>
    Friend Shared ReadOnly Property lblCUSTODYCD() As String
        Get
            Return ResourceManager.GetString("lblCUSTODYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sàn giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property lblExecType() As String
        Get
            Return ResourceManager.GetString("lblExecType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số CMT:.
    '''</summary>
    Friend Shared ReadOnly Property lblIDCODE() As String
        Get
            Return ResourceManager.GetString("lblIDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Phương thức khớp:.
    '''</summary>
    Friend Shared ReadOnly Property lblMatchType() As String
        Get
            Return ResourceManager.GetString("lblMatchType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số ĐT.
    '''</summary>
    Friend Shared ReadOnly Property lblMOBILE() As String
        Get
            Return ResourceManager.GetString("lblMOBILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số mobile 2/Cố định:.
    '''</summary>
    Friend Shared ReadOnly Property lblMOBILE1() As String
        Get
            Return ResourceManager.GetString("lblMOBILE1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số mobile 1:.
    '''</summary>
    Friend Shared ReadOnly Property lblMOBILESMS() As String
        Get
            Return ResourceManager.GetString("lblMOBILESMS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tên:.
    '''</summary>
    Friend Shared ReadOnly Property lblName() As String
        Get
            Return ResourceManager.GetString("lblName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to PIN:.
    '''</summary>
    Friend Shared ReadOnly Property lblPIN() As String
        Get
            Return ResourceManager.GetString("lblPIN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã pin: .
    '''</summary>
    Friend Shared ReadOnly Property lblPinValidate() As String
        Get
            Return ResourceManager.GetString("lblPinValidate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giá:.
    '''</summary>
    Friend Shared ReadOnly Property lblPrice() As String
        Get
            Return ResourceManager.GetString("lblPrice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Khối lượng.
    '''</summary>
    Friend Shared ReadOnly Property lblQuantity() As String
        Get
            Return ResourceManager.GetString("lblQuantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Danh mục chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property lblSE() As String
        Get
            Return ResourceManager.GetString("lblSE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chứng khoán:.
    '''</summary>
    Friend Shared ReadOnly Property lblSymbol() As String
        Get
            Return ResourceManager.GetString("lblSymbol", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sàn giao dịch:.
    '''</summary>
    Friend Shared ReadOnly Property lblTradePlace() As String
        Get
            Return ResourceManager.GetString("lblTradePlace", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cầm cố.
    '''</summary>
    Friend Shared ReadOnly Property MORTAGE() As String
        Get
            Return ResourceManager.GetString("MORTAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tổng nợ.
    '''</summary>
    Friend Shared ReadOnly Property OUTSTANDING() As String
        Get
            Return ResourceManager.GetString("OUTSTANDING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mật khẩu.
    '''</summary>
    Friend Shared ReadOnly Property PASSWORD() As String
        Get
            Return ResourceManager.GetString("PASSWORD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số điện thoại 1.
    '''</summary>
    Friend Shared ReadOnly Property PHONE1() As String
        Get
            Return ResourceManager.GetString("PHONE1", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số điện thoại 2.
    '''</summary>
    Friend Shared ReadOnly Property PHONE2() As String
        Get
            Return ResourceManager.GetString("PHONE2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số điện thoại 3.
    '''</summary>
    Friend Shared ReadOnly Property PHONE3() As String
        Get
            Return ResourceManager.GetString("PHONE3", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số điện thoại 4.
    '''</summary>
    Friend Shared ReadOnly Property PHONE4() As String
        Get
            Return ResourceManager.GetString("PHONE4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thặng dư tài sản.
    '''</summary>
    Friend Shared ReadOnly Property PP() As String
        Get
            Return ResourceManager.GetString("PP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chờ về.
    '''</summary>
    Friend Shared ReadOnly Property RECEIVING() As String
        Get
            Return ResourceManager.GetString("RECEIVING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số tiểu khoản : .
    '''</summary>
    Friend Shared ReadOnly Property s_ACCOUNT() As String
        Get
            Return ResourceManager.GetString("s_ACCOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Họ và tên : .
    '''</summary>
    Friend Shared ReadOnly Property s_FULLNAME() As String
        Get
            Return ResourceManager.GetString("s_FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số chứng thư : .
    '''</summary>
    Friend Shared ReadOnly Property s_IDCODE() As String
        Get
            Return ResourceManager.GetString("s_IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Số điện thoại 1|2 : .
    '''</summary>
    Friend Shared ReadOnly Property s_PHONE() As String
        Get
            Return ResourceManager.GetString("s_PHONE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mã pin chính xác!.
    '''</summary>
    Friend Shared ReadOnly Property SSS_Corecct() As String
        Get
            Return ResourceManager.GetString("SSS_Corecct", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Đẩy lệnh thành công!.
    '''</summary>
    Friend Shared ReadOnly Property SUCCESFULL() As String
        Get
            Return ResourceManager.GetString("SUCCESFULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chứng khoán.
    '''</summary>
    Friend Shared ReadOnly Property SYMBOL() As String
        Get
            Return ResourceManager.GetString("SYMBOL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Giao dịch.
    '''</summary>
    Friend Shared ReadOnly Property TRADE() As String
        Get
            Return ResourceManager.GetString("TRADE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chưa đăng ký giao dịch qua điện thoại.
    '''</summary>
    Friend Shared ReadOnly Property TRADETELEPHONE() As String
        Get
            Return ResourceManager.GetString("TRADETELEPHONE", resourceCulture)
        End Get
    End Property
End Class
