'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmUpcomSendingConfirm_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_DIRECT.frmUpcomSendingConfirm-EN", GetType(frmUpcomSendingConfirm_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Exit.
    '''</summary>
    Friend Shared ReadOnly Property _Exit() As String
        Get
            Return ResourceManager.GetString("Exit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid: Adjust quantity over original quantity!.
    '''</summary>
    Friend Shared ReadOnly Property AdjustQttyOverOrgQtty() As String
        Get
            Return ResourceManager.GetString("AdjustQttyOverOrgQtty", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amend.
    '''</summary>
    Friend Shared ReadOnly Property Amend() As String
        Get
            Return ResourceManager.GetString("Amend", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amendment.
    '''</summary>
    Friend Shared ReadOnly Property Amendment() As String
        Get
            Return ResourceManager.GetString("Amendment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amendment order.
    '''</summary>
    Friend Shared ReadOnly Property Amendmentorder() As String
        Get
            Return ResourceManager.GetString("Amendmentorder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to AMEND.
    '''</summary>
    Friend Shared ReadOnly Property AMENDS() As String
        Get
            Return ResourceManager.GetString("AMENDS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve Amendment .
    '''</summary>
    Friend Shared ReadOnly Property ApproveAmendment() As String
        Get
            Return ResourceManager.GetString("ApproveAmendment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approve Cancel.
    '''</summary>
    Friend Shared ReadOnly Property ApproveCancel() As String
        Get
            Return ResourceManager.GetString("ApproveCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to approve?.
    '''</summary>
    Friend Shared ReadOnly Property ApproveConfirm() As String
        Get
            Return ResourceManager.GetString("ApproveConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Approved Successful.
    '''</summary>
    Friend Shared ReadOnly Property ApproveSuccessful() As String
        Get
            Return ResourceManager.GetString("ApproveSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Back.
    '''</summary>
    Friend Shared ReadOnly Property Back() As String
        Get
            Return ResourceManager.GetString("Back", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Allocate.
    '''</summary>
    Friend Shared ReadOnly Property btnAllocate() As String
        Get
            Return ResourceManager.GetString("btnAllocate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property btnCancel() As String
        Get
            Return ResourceManager.GetString("btnCancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Down.
    '''</summary>
    Friend Shared ReadOnly Property btnDOWN() As String
        Get
            Return ResourceManager.GetString("btnDOWN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ?.
    '''</summary>
    Friend Shared ReadOnly Property btnGetDeal() As String
        Get
            Return ResourceManager.GetString("btnGetDeal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;OK.
    '''</summary>
    Friend Shared ReadOnly Property btnOK() As String
        Get
            Return ResourceManager.GetString("btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Refuse.
    '''</summary>
    Friend Shared ReadOnly Property btnRefuse() As String
        Get
            Return ResourceManager.GetString("btnRefuse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Send.
    '''</summary>
    Friend Shared ReadOnly Property btnSend() As String
        Get
            Return ResourceManager.GetString("btnSend", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Up.
    '''</summary>
    Friend Shared ReadOnly Property btnUP() As String
        Get
            Return ResourceManager.GetString("btnUP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel.
    '''</summary>
    Friend Shared ReadOnly Property Cancel() As String
        Get
            Return ResourceManager.GetString("Cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Confirm.
    '''</summary>
    Friend Shared ReadOnly Property Confirm() As String
        Get
            Return ResourceManager.GetString("Confirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Custody Code : .
    '''</summary>
    Friend Shared ReadOnly Property CustodyCode() As String
        Get
            Return ResourceManager.GetString("CustodyCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer Name: .
    '''</summary>
    Friend Shared ReadOnly Property CustomerName() As String
        Get
            Return ResourceManager.GetString("CustomerName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Deal.
    '''</summary>
    Friend Shared ReadOnly Property DEALINVALID() As String
        Get
            Return ResourceManager.GetString("DEALINVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid amount.
    '''</summary>
    Friend Shared ReadOnly Property ERR_ADDQTTY_INVALID() As String
        Get
            Return ResourceManager.GetString("ERR_ADDQTTY_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Amount.
    '''</summary>
    Friend Shared ReadOnly Property ERR_AMT_INFO() As String
        Get
            Return ResourceManager.GetString("ERR_AMT_INFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Executed.
    '''</summary>
    Friend Shared ReadOnly Property Executed() As String
        Get
            Return ResourceManager.GetString("Executed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order sending confirm.
    '''</summary>
    Friend Shared ReadOnly Property frmOrderSendingConfirm() As String
        Get
            Return ResourceManager.GetString("frmOrderSendingConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to DF group asset details.
    '''</summary>
    Friend Shared ReadOnly Property frmViewDFMAST() As String
        Get
            Return ResourceManager.GetString("frmViewDFMAST", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid adjust quantity!.
    '''</summary>
    Friend Shared ReadOnly Property Invalidadjustquantity() As String
        Get
            Return ResourceManager.GetString("Invalidadjustquantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid matched quantity!.
    '''</summary>
    Friend Shared ReadOnly Property Invalidmatchedquantity() As String
        Get
            Return ResourceManager.GetString("Invalidmatchedquantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid numeric field !.
    '''</summary>
    Friend Shared ReadOnly Property Invalidnumeric() As String
        Get
            Return ResourceManager.GetString("Invalidnumeric", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid trade lot!.
    '''</summary>
    Friend Shared ReadOnly Property Invalidtradelot() As String
        Get
            Return ResourceManager.GetString("Invalidtradelot", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID Type.
    '''</summary>
    Friend Shared ReadOnly Property lblAcType() As String
        Get
            Return ResourceManager.GetString("lblAcType", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Paid amount.
    '''</summary>
    Friend Shared ReadOnly Property lblAMTPAID() As String
        Get
            Return ResourceManager.GetString("lblAMTPAID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Balance.
    '''</summary>
    Friend Shared ReadOnly Property lblCURAMT() As String
        Get
            Return ResourceManager.GetString("lblCURAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Deal.
    '''</summary>
    Friend Shared ReadOnly Property lblDealNo() As String
        Get
            Return ResourceManager.GetString("lblDealNo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property lblDescription() As String
        Get
            Return ResourceManager.GetString("lblDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current OutStanding.
    '''</summary>
    Friend Shared ReadOnly Property lblDFAMT() As String
        Get
            Return ResourceManager.GetString("lblDFAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Safe Ratio.
    '''</summary>
    Friend Shared ReadOnly Property lblIRATE() As String
        Get
            Return ResourceManager.GetString("lblIRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Penalty fee.
    '''</summary>
    Friend Shared ReadOnly Property lbllPAIDPENAFEE() As String
        Get
            Return ResourceManager.GetString("lbllPAIDPENAFEE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trigger Ratio.
    '''</summary>
    Friend Shared ReadOnly Property lblLRATE() As String
        Get
            Return ResourceManager.GetString("lblLRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Warning Ratio.
    '''</summary>
    Friend Shared ReadOnly Property lblMRATE() As String
        Get
            Return ResourceManager.GetString("lblMRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Paying AMT.
    '''</summary>
    Friend Shared ReadOnly Property lblPAIDAMT() As String
        Get
            Return ResourceManager.GetString("lblPAIDAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Paying Service Fee.
    '''</summary>
    Friend Shared ReadOnly Property lblPAIDFEE() As String
        Get
            Return ResourceManager.GetString("lblPAIDFEE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Paying interest.
    '''</summary>
    Friend Shared ReadOnly Property lblPAIDINT() As String
        Get
            Return ResourceManager.GetString("lblPAIDINT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Service Fee.
    '''</summary>
    Friend Shared ReadOnly Property lblTOTALFEE() As String
        Get
            Return ResourceManager.GetString("lblTOTALFEE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current interest.
    '''</summary>
    Friend Shared ReadOnly Property lblTOTALINT() As String
        Get
            Return ResourceManager.GetString("lblTOTALINT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Penalty fee.
    '''</summary>
    Friend Shared ReadOnly Property lblTOTALPENAFEE() As String
        Get
            Return ResourceManager.GetString("lblTOTALPENAFEE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sum Loan.
    '''</summary>
    Friend Shared ReadOnly Property lblTTLOAN() As String
        Get
            Return ResourceManager.GetString("lblTTLOAN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actual ratio.
    '''</summary>
    Friend Shared ReadOnly Property lblTTRATE() As String
        Get
            Return ResourceManager.GetString("lblTTRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Matched.
    '''</summary>
    Friend Shared ReadOnly Property Matched() As String
        Get
            Return ResourceManager.GetString("Matched", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order Quantity can not greater than root Order Quantity.
    '''</summary>
    Friend Shared ReadOnly Property OrderQuantityCannotGreaterQTTY() As String
        Get
            Return ResourceManager.GetString("OrderQuantityCannotGreaterQTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Order Quantity can not less than zero.
    '''</summary>
    Friend Shared ReadOnly Property OrderQuantityCannotLessZero() As String
        Get
            Return ResourceManager.GetString("OrderQuantityCannotLessZero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Original order.
    '''</summary>
    Friend Shared ReadOnly Property OriginalOrder() As String
        Get
            Return ResourceManager.GetString("OriginalOrder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price.
    '''</summary>
    Friend Shared ReadOnly Property Price() As String
        Get
            Return ResourceManager.GetString("Price", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity.
    '''</summary>
    Friend Shared ReadOnly Property Quantity() As String
        Get
            Return ResourceManager.GetString("Quantity", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure to refuse?.
    '''</summary>
    Friend Shared ReadOnly Property RefuseConfirm() As String
        Get
            Return ResourceManager.GetString("RefuseConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refuse successful!.
    '''</summary>
    Friend Shared ReadOnly Property RefusedSuccessful() As String
        Get
            Return ResourceManager.GetString("RefusedSuccessful", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Send.
    '''</summary>
    Friend Shared ReadOnly Property Send() As String
        Get
            Return ResourceManager.GetString("Send", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settlement cycle: .
    '''</summary>
    Friend Shared ReadOnly Property SettlementCycle() As String
        Get
            Return ResourceManager.GetString("SettlementCycle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property txtDescription() As String
        Get
            Return ResourceManager.GetString("txtDescription", resourceCulture)
        End Get
    End Property
End Class
