'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmContractInfo_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmContractInfo-EN", GetType(frmContractInfo_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contract information.
    '''</summary>
    Friend Shared ReadOnly Property frmContractInfo() As String
        Get
            Return ResourceManager.GetString("frmContractInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Close.
    '''</summary>
    Friend Shared ReadOnly Property frmContractInfo_btnCANCEL() As String
        Get
            Return ResourceManager.GetString("frmContractInfo.btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Ok.
    '''</summary>
    Friend Shared ReadOnly Property frmContractInfo_btnOK() As String
        Get
            Return ResourceManager.GetString("frmContractInfo.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to There is no data item found from this point to the end of list!.
    '''</summary>
    Friend Shared ReadOnly Property frmContractInfo_SearchConfirm() As String
        Get
            Return ResourceManager.GetString("frmContractInfo.SearchConfirm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Address.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_ADDRESS() As String
        Get
            Return ResourceManager.GetString("MEMBER_ADDRESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer code.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_CUSTID() As String
        Get
            Return ResourceManager.GetString("MEMBER_CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Effective date.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_EFFDATE() As String
        Get
            Return ResourceManager.GetString("MEMBER_EFFDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expired date.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_EXPDATE() As String
        Get
            Return ResourceManager.GetString("MEMBER_EXPDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fullname.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_FULLNAME() As String
        Get
            Return ResourceManager.GetString("MEMBER_FULLNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Identifycation code.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDCODE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID date.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDDATE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ID place.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_IDPLACE() As String
        Get
            Return ResourceManager.GetString("MEMBER_IDPLACE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reference.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_REF() As String
        Get
            Return ResourceManager.GetString("MEMBER_REF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property MEMBER_TYP() As String
        Get
            Return ResourceManager.GetString("MEMBER_TYP", resourceCulture)
        End Get
    End Property
End Class
