'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class frmPostmap_EN
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppCore.frmPostmap-EN", GetType(frmPostmap_EN).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer&apos;s id is invalid. Press F5 and correct data!.
    '''</summary>
    Friend Shared ReadOnly Property CUSTID_INVALID() As String
        Get
            Return ResourceManager.GetString("CUSTID_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Make account entry.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap() As String
        Get
            Return ResourceManager.GetString("frmPostmap", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account Name.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_ACCTNAME() As String
        Get
            Return ResourceManager.GetString("frmPostmap.ACCTNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account No.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_ACCTNO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.ACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Address.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_ADDRESS() As String
        Get
            Return ResourceManager.GetString("frmPostmap.ADDRESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_AMT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.AMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Add entry.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_btnAdd() As String
        Get
            Return ResourceManager.GetString("frmPostmap.btnAdd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Cancel.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_btnCANCEL() As String
        Get
            Return ResourceManager.GetString("frmPostmap.btnCANCEL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Delete entry.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_btnDelete() As String
        Get
            Return ResourceManager.GetString("frmPostmap.btnDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Edit entry.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_btnEdit() As String
        Get
            Return ResourceManager.GetString("frmPostmap.btnEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &amp;Ok.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_btnOK() As String
        Get
            Return ResourceManager.GetString("frmPostmap.btnOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Credit amount.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_CAMOUNT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.CAMOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Currency.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_CCYCD() As String
        Get
            Return ResourceManager.GetString("frmPostmap.CCYCD", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Contents.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_CONTENTS() As String
        Get
            Return ResourceManager.GetString("frmPostmap.CONTENTS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer id.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_CUSTID() As String
        Get
            Return ResourceManager.GetString("frmPostmap.CUSTID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Customer name.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_CUSTNAME() As String
        Get
            Return ResourceManager.GetString("frmPostmap.CUSTNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Debit amount.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_DAMOUNT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.DAMOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Department.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_DEPARTMENT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.DEPARTMENT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_DESC() As String
        Get
            Return ResourceManager.GetString("frmPostmap.DESC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Description.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_DESCRIPTION() As String
        Get
            Return ResourceManager.GetString("frmPostmap.DESCRIPTION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Debit/Credit.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_DORC() As String
        Get
            Return ResourceManager.GetString("frmPostmap.DORC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Income/Expense.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_FEEID() As String
        Get
            Return ResourceManager.GetString("frmPostmap.FEEID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account name.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblACCTNAME() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblACCTNAME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account number.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblACCTNO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblACCTNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amount.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblAMOUNT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblAMOUNT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Input postmap for GL transaction..
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblCaption() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblCaption", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Press Delete key for delete current row!.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblFunction() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblFunction", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_lblSUBTXNO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.lblSUBTXNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_PRICE() As String
        Get
            Return ResourceManager.GetString("frmPostmap.PRICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_QTTY() As String
        Get
            Return ResourceManager.GetString("frmPostmap.QTTY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Credit.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_rbCredit() As String
        Get
            Return ResourceManager.GetString("frmPostmap.rbCredit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Debit.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_rbDebit() As String
        Get
            Return ResourceManager.GetString("frmPostmap.rbDebit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Serie.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_SERIENO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.SERIENO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_SUBTXNO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.SUBTXNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Task.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_TASK() As String
        Get
            Return ResourceManager.GetString("frmPostmap.TASK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tax code.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_TAXCODE() As String
        Get
            Return ResourceManager.GetString("frmPostmap.TAXCODE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account entries.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_tpgAccountEntries() As String
        Get
            Return ResourceManager.GetString("frmPostmap.tpgAccountEntries", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fixed assest.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_tpgFixedAssest() As String
        Get
            Return ResourceManager.GetString("frmPostmap.tpgFixedAssest", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT voucher.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_tpgVATVoucher() As String
        Get
            Return ResourceManager.GetString("frmPostmap.tpgVATVoucher", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT amount.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_VATAMT() As String
        Get
            Return ResourceManager.GetString("frmPostmap.VATAMT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT rate.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_VATRATE() As String
        Get
            Return ResourceManager.GetString("frmPostmap.VATRATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Date.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_VOUCHERDATE() As String
        Get
            Return ResourceManager.GetString("frmPostmap.VOUCHERDATE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No..
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_VOUCHERNO() As String
        Get
            Return ResourceManager.GetString("frmPostmap.VOUCHERNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Type.
    '''</summary>
    Friend Shared ReadOnly Property frmPostmap_VOUCHERTYPE() As String
        Get
            Return ResourceManager.GetString("frmPostmap.VOUCHERTYPE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cannot init VAT voucher grid!.
    '''</summary>
    Friend Shared ReadOnly Property INIT_VAT_POSTMAP_FAILED() As String
        Get
            Return ResourceManager.GetString("INIT_VAT_POSTMAP_FAILED", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Price data is invalid!.
    '''</summary>
    Friend Shared ReadOnly Property PRICE_INVALID() As String
        Get
            Return ResourceManager.GetString("PRICE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quantity data is invalid!.
    '''</summary>
    Friend Shared ReadOnly Property QTTY_INVALID() As String
        Get
            Return ResourceManager.GetString("QTTY_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to VAT rate is invalid!.
    '''</summary>
    Friend Shared ReadOnly Property VATRATE_INVALID() As String
        Get
            Return ResourceManager.GetString("VATRATE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Voucher date is invalid. Please re-type it!.
    '''</summary>
    Friend Shared ReadOnly Property VOUCHERDATE_INVALID() As String
        Get
            Return ResourceManager.GetString("VOUCHERDATE_INVALID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Voucher type is invalid. Press F5 and correct data!.
    '''</summary>
    Friend Shared ReadOnly Property VOUCHERTYPE_INVALID() As String
        Get
            Return ResourceManager.GetString("VOUCHERTYPE_INVALID", resourceCulture)
        End Get
    End Property
End Class
